### ISSUE TITLE
Refactoring handling httpResponse in Java Engine

### ISSUE THREAD

**Issue by lennon310** [SeldonIO/seldon-core#1075]
With this ressponse:

```
status = {"code": 400, "reason": "sth goes wrong", "status": "FAILURE", "info": "test in exception"}
return {"data": {"names": ["score"], "ndarray": scores}, "status": status}
``` 

from model prediction, the `queryREST` throws exception at its Spring [post method](https://github.com/SeldonIO/seldon-core/blob/master/engine/src/main/java/io/seldon/engine/service/InternalPredictionService.java#L492), and the log looks like:

```
ring-web-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.2.0.
RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:785) ~[spring-web-5.2.0.RELEASE.jar!
/:5.2.0.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:743) ~[spring-web-5.2.0.RELEASE.jar!/:5.2
.0.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717) ~[spring-web-5.2.0.RELEASE.jar!/:5.2.0
.RELEASE]
        at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:470) ~[spring-web-5.2.0.RELEASE.jar!/
:5.2.0.RELEASE]
        at io.seldon.engine.service.InternalPredictionService.queryREST(InternalPredictionService.java:492) ~[classes!/:0.5.
0]
        at io.seldon.engine.service.InternalPredictionService.transformInput(InternalPredictionService.java:290) ~[classes!/
:0.5.0]
        at io.seldon.engine.predictors.PredictiveUnitBean.transformInput(PredictiveUnitBean.java:257) ~[classes!/:0.5.0]
        at io.seldon.engine.predictors.PredictiveUnitBean.getOutputAsync(PredictiveUnitBean.java:134) ~[classes!/:0.5.0]
        at io.seldon.engine.predictors.PredictiveUnitBean$$FastClassBySpringCGLIB$$ddb0d27b.invoke(<generated>) ~[classes!/:
0.5.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.0.RELEASE.jar!/:5.2.0.
RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[s
pring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[sprin
g-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-ao
p-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
 ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
``` 

That means the [error message parsing](https://github.com/SeldonIO/seldon-core/blob/master/engine/src/main/java/io/seldon/engine/service/InternalPredictionService.java#L501-L518) is not implemented if it's an non-200 response. We should probably consider moving this exception handling inside this [catch block](https://github.com/SeldonIO/seldon-core/blob/master/engine/src/main/java/io/seldon/engine/service/InternalPredictionService.java#L534). 

Besides, we should decide what [status code](https://github.com/SeldonIO/seldon-core/blob/master/engine/src/main/java/io/seldon/engine/service/InternalPredictionService.java#L515) we want to use to wrap the ApiException into a `SeldonMessage`. I understand the concern a 200 code doesn't seem like a failure response here, I was setting it to 200 since our service call builder doesn't support deserialization on an non-200 `SeldonMessage` response.

**Comment by cliveseldon** [comment]
Any input on this @axsaucedo @adriangonz ?

**Comment by axsaucedo** [comment]
This is certainly something we should implement - this has been brought up previously (i.e. #939). I think we should try to incorporate this into 1.0 if we can, probably something to tackle after the JSON float/int piece.

**Comment by lennon310** [comment]
@axsaucedo because this line throws exception directly if the http status code is non-200:

```
ResponseEntity<String> httpResponse =
            restTemplate.postForEntity(uri, request, String.class);
```

I was wondering whether there is a way we could still retrieve the response body from there?

**Comment by lennon310** [comment]
I created a PR trying to address the issue of post entity error handling, temporarily leaving the status code as it is since we are still under discussion.

**Comment by adriangonz** [comment]
@lennon310 now that #1117 is merged, do you consider this solved?

Regarding the status code, I'm inclined to leave it as it is for now, since that's the current documented behaviour.

**Comment by lennon310** [comment]
@adriangonz I'm trying to create an integration test on its behavior, shall we close the issue after that?

**Comment by lennon310** [comment]
Added [one integration test](https://github.com/SeldonIO/seldon-core/pull/1132). Closing this issue.
