### ISSUE TITLE
Seldon wrapper image with python 3.8

### ISSUE THREAD

**Issue by SebBlin** [SeldonIO/seldon-core#1230]
I need to integrate a personal library in Seldon and that library requires python 3.8 to work properly with seldon micro-service.
Would it be possible to produce an additional seldon wrapper image based on python 3.8 ?

Regards

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by RafalSkolasinski** [comment]
As a warning note: it was reported that starting seldon core microservice leads to pickle error on Python 3.8.1
```
2020-07-06 09:38:19,130 - seldon_core.microservice:main:420 - INFO:  Starting servers
Traceback (most recent call last):
  File "/Users/willb/.local/share/virtualenvs/test-LcpKI1FQ/bin/seldon-core-microservice", line 8, in <module>
    sys.exit(main())
  File "/Users/willb/.local/share/virtualenvs/test-LcpKI1FQ/lib/python3.8/site-packages/seldon_core/microservice.py", line 421, in main
    start_servers(server1_func, server2_func, metrics_server_func)
  File "/Users/willb/.local/share/virtualenvs/test-LcpKI1FQ/lib/python3.8/site-packages/seldon_core/microservice.py", line 54, in start_servers
    p3.start()
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.rest_metrics_server'
```

Unfortunately we couldn't reproduce the issue on our side: seems it may be some nuances related to starting a Python subprocess  on MacOS.

**Comment by RafalSkolasinski** [comment]
Wonder if we should try to make Python 3.8 a default now? 
@axsaucedo @cliveseldon, what do you think?

If we move master to be 3.8 by default now there should be plenty of time to test it in action before 1.3 release.

**Comment by cliveseldon** [comment]
Worth investigating also for #2324 
We might need to redo all the example saved Alibi images though as unpickling can hit issues between python versions.

**Comment by RafalSkolasinski** [comment]
Ah, yes, the default pickling protocol changed.
