### ISSUE TITLE
Segmentation violation in seldon operator

### ISSUE THREAD

**Issue by maximmold** [SeldonIO/seldon-core#1359]
Using the latest 1.0 kubeflow release candidate and seldon 0.4.1 operator, I get this error when trying to process a new seldon deployment.

```panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xfc1f20]

goroutine 63 [running]:
github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x1149620, 0x1b88eb0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/seldonio/seldon-operator/pkg/controller/seldondeployment.addModelDefaultServers(0xc42050d9c0, 0xc4208d0240, 0xc420257b00, 0xc4203d2d80, 0xc4204a7060, 0x1)
	/go/src/github.com/seldonio/seldon-operator/pkg/controller/seldondeployment/seldondeployment_prepackaged_servers.go:110 +0x40
github.com/seldonio/seldon-operator/pkg/controller/seldondeployment.createStandaloneModelServers(0xc42050d9c0, 0xc4200d7ba0, 0xc420257b00, 0xc42087e380, 0xc4208d0240, 0xc4204a70a8, 0x0)
	/go/src/github.com/seldonio/seldon-operator/pkg/controller/seldondeployment/seldondeployment_prepackaged_servers.go:273 +0x1bf
github.com/seldonio/seldon-operator/pkg/controller/seldondeployment.createComponents(0xc42050d9c0, 0xc4200d7ba0, 0xc420046100, 0xc42098e1a0, 0x8)
	/go/src/github.com/seldonio/seldon-operator/pkg/controller/seldondeployment/seldondeployment_controller.go:437 +0xa9c
github.com/seldonio/seldon-operator/pkg/controller/seldondeployment.(*ReconcileSeldonDeployment).Reconcile(0xc42050d9c0, 0xc42098e1a0, 0x8, 0xc4208ce820, 0x1b, 0x1b9c040, 0x1, 0xc42006d6b8, 0x43a3f2)
	/go/src/github.com/seldonio/seldon-operator/pkg/controller/seldondeployment/seldondeployment_controller.go:1169 +0x17b
github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc42018c3c0, 0x0)
	/go/src/github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x188
github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/go/src/github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4208933d0)
	/go/src/github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4208933d0, 0x3b9aca00, 0x0, 0x1, 0xc4203f0120)
	/go/src/github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4208933d0, 0x3b9aca00, 0xc4203f0120)
	/go/src/github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/src/github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x35b
```

My deployment looks like this

```
apiVersion: v1
items:
- apiVersion: machinelearning.seldon.io/v1alpha3
  kind: SeldonDeployment
  metadata:
    creationTimestamp: "2020-01-22T14:30:07Z"
    generation: 1
    labels:
      app: seldon
    name: seldon-deployment-nlp-4wqr5
    namespace: kubeflow
    resourceVersion: "56827"
    selfLink: /apis/machinelearning.seldon.io/v1alpha3/namespaces/kubeflow/seldondeployments/seldon-deployment-nlp-4wqr5
    uid: 35f49d91-ae85-4307-824a-ea88ebce818f
  spec:
    annotations:
      deployment_version: v1
      project_name: NLP Pipeline
    name: seldon-deployment-nlp-4wqr5
    oauth_key: oauth-key
    oauth_secret: oauth-secret
    predictors:
    - annotations:
        predictor_version: v1
      componentSpecs:
      - spec:
          containers:
          - image: clean_text_transformer:0.1
            imagePullPolicy: IfNotPresent
            name: cleantext
            resources:
              requests:
                memory: 1Mi
          - image: spacy_tokenizer:0.1
            imagePullPolicy: IfNotPresent
            name: spacytokenizer
          - image: tfidf_vectorizer:0.1
            imagePullPolicy: IfNotPresent
            name: tfidfvectorizer
            volumeMounts:
            - mountPath: /mnt
              name: mypvc
          - image: lr_text_classifier:0.1
            imagePullPolicy: IfNotPresent
            name: lrclassifier
            volumeMounts:
            - mountPath: /mnt
              name: mypvc
          terminationGracePeriodSeconds: 20
          volumes:
          - name: mypvc
            persistentVolumeClaim:
              claimName: nlp-4wqr5-my-pvc
      graph:
        children:
        - children:
          - children:
            - children: []
              endpoint:
                type: REST
              name: lrclassifier
              type: MODEL
            endpoint:
              type: REST
            name: tfidfvectorizer
            type: MODEL
          endpoint:
            type: REST
          name: spacytokenizer
          type: MODEL
        endpoint:
          type: REST
        name: cleantext
        type: MODEL
      name: single-model
      replicas: 1
- apiVersion: machinelearning.seldon.io/v1alpha3
  kind: SeldonDeployment
  metadata:
    creationTimestamp: "2020-01-22T14:35:32Z"
    generation: 1
    labels:
      app: seldon
    name: seldon-deployment-nlp-t29kf
    namespace: kubeflow
    resourceVersion: "59052"
    selfLink: /apis/machinelearning.seldon.io/v1alpha3/namespaces/kubeflow/seldondeployments/seldon-deployment-nlp-t29kf
    uid: 14153de2-85d6-4d0e-b738-8f8e5d4fe045
  spec:
    annotations:
      deployment_version: v1
      project_name: NLP Pipeline
    name: seldon-deployment-nlp-t29kf
    oauth_key: oauth-key
    oauth_secret: oauth-secret
    predictors:
    - annotations:
        predictor_version: v1
      componentSpecs:
      - spec:
          containers:
          - image: clean_text_transformer:0.1
            imagePullPolicy: IfNotPresent
            name: cleantext
            resources:
              requests:
                memory: 1Mi
          - image: spacy_tokenizer:0.1
            imagePullPolicy: IfNotPresent
            name: spacytokenizer
          - image: tfidf_vectorizer:0.1
            imagePullPolicy: IfNotPresent
            name: tfidfvectorizer
            volumeMounts:
            - mountPath: /mnt
              name: mypvc
          - image: lr_text_classifier:0.1
            imagePullPolicy: IfNotPresent
            name: lrclassifier
            volumeMounts:
            - mountPath: /mnt
              name: mypvc
          terminationGracePeriodSeconds: 20
          volumes:
          - name: mypvc
            persistentVolumeClaim:
              claimName: nlp-t29kf-my-pvc
      graph:
        children:
        - children:
          - children:
            - children: []
              endpoint:
                type: REST
              name: lrclassifier
              type: MODEL
            endpoint:
              type: REST
            name: tfidfvectorizer
            type: MODEL
          endpoint:
            type: REST
          name: spacytokenizer
          type: MODEL
        endpoint:
          type: REST
        name: cleantext
        type: MODEL
      name: single-model
      replicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""```

I am following this guide. https://github.com/SeldonIO/seldon-core/tree/master/examples/kubeflow

**Comment by maximmold** [comment]
I am not seeing this now that I switch to 0.7.1 and got past an issue on the kfctl side.

**Comment by cliveseldon** [comment]
Glad it working this might happen if the webhook was not installed correcly and thus not called by the k8s api server.
