### ISSUE TITLE
test_no_permission_bucket_gcs fails when run locally

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1364]
```python
______________________________________________________________________________________________________________________________________________ test_no_permission_buckets_gcs _______________________________________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/rskolasinski/work/seldon-core/python/tests/test_storage.py", line 90, in test_no_permission_buckets_gcs
    seldon_core.Storage.download(bad_gcs_path)
  File "/home/rskolasinski/work/seldon-core/python/seldon_core/storage.py", line 56, in download
    Storage._download_gcs(uri, out_dir)
  File "/home/rskolasinski/work/seldon-core/python/seldon_core/storage.py", line 108, in _download_gcs
    for blob in blobs:
  File "/home/rskolasinski/miniconda3/envs/seldon-core-dev/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 212, in _items_iter
    for page in self._page_iter(increment=False):
  File "/home/rskolasinski/miniconda3/envs/seldon-core-dev/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 243, in _page_iter
    page = self._next_page()
  File "/home/rskolasinski/miniconda3/envs/seldon-core-dev/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 369, in _next_page
    response = self._get_next_page_response()
  File "/home/rskolasinski/miniconda3/envs/seldon-core-dev/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 419, in _get_next_page_response
    method=self._HTTP_METHOD, path=self.path, query_params=params
  File "/home/rskolasinski/miniconda3/envs/seldon-core-dev/lib/python3.7/site-packages/google/cloud/_http.py", line 417, in api_request
    timeout=timeout,
  File "/home/rskolasinski/miniconda3/envs/seldon-core-dev/lib/python3.7/site-packages/google/cloud/_http.py", line 275, in _make_request
    method, url, headers, data, target_object, timeout=timeout
  File "/home/rskolasinski/miniconda3/envs/seldon-core-dev/lib/python3.7/site-packages/google/cloud/_http.py", line 313, in _do_request
    url=url, method=method, headers=headers, data=data, timeout=timeout
  File "/home/rskolasinski/miniconda3/envs/seldon-core-dev/lib/python3.7/site-packages/google/auth/transport/requests.py", line 347, in request
    self.credentials.refresh(auth_request)
  File "/home/rskolasinski/miniconda3/envs/seldon-core-dev/lib/python3.7/site-packages/google/auth/credentials.py", line 148, in refresh
    raise ValueError("Anonymous credentials cannot be refreshed.")
ValueError: Anonymous credentials cannot be refreshed.
```

**Comment by adriangonz** [comment]
I was just looking into this. I believe it's due to the GCS environment variables set on the local environment.

**Comment by adriangonz** [comment]
After spending a bit of time on this, my understanding is that the following line requires GCP's Application Default Credentials set up in your environment:
https://github.com/SeldonIO/seldon-core/blob/3b1e50368523e31278b1f5f5657ed28f5883f0cc/python/seldon_core/storage.py#L97

If they are not present, it falls back to an "anonymous client" which causes the `Anonymous credentials cannot be refreshed` error you showed above. The CI probably still works because it's running on GCP and it has a service account set up.

We should try to provide some fake GCP credentials or to mock whatever is doing the authentication inside the `storage.Client()` class.

**Comment by RafalSkolasinski** [comment]
@adriangonz Do you observe same failure on your side when running this locally? 
I just wonder if this is something very specific to my environment or generic thing.

**Comment by adriangonz** [comment]
@RafalSkolasinski as it is, it's specific to the local environment. It would be good to mock the relevant bits so that it doesn't look at your environment.

**Comment by cliveseldon** [comment]
Can we close this @RafalSkolasinski ?

**Comment by RafalSkolasinski** [comment]
It is still failing for me every time I run tests locally but if this is only for me we can close it, yes.
