### ISSUE TITLE
add tests for tracing-enabled code path in executor's rest API

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1858]
Commenting out for example a following block of code
https://github.com/SeldonIO/seldon-core/blob/787bb8b510f9590b05d3118395ac5e2a9e5c89fc/executor/api/rest/server.go#L304-L309
will not fail tests but will lead to obscure errors on prediction request.

Bellow example (using (new) metadata endpoint without the tracing code block):
```
{"level":"info","ts":1589987540.2213755,"logger":"SeldonRestApi","msg":"Graph Metadata called."}
{"level":"info","ts":1589987540.221461,"logger":"JSONRestClient","msg":"Calling HTTP","URL":"http://0.0.0.0:9001/metadata"}
2020/05/20 16:12:20 http: panic serving 127.0.0.1:42208: runtime error: invalid memory address or nil pointer dereference
goroutine 40 [running]:
net/http.(*conn).serve.func1(0xc0003c4000)
	/usr/lib/go-1.14/src/net/http/server.go:1772 +0x139
panic(0x1580900, 0x25f3140)
	/usr/lib/go-1.14/src/runtime/panic.go:975 +0x3e3
github.com/seldonio/seldon-core/executor/api/rest.(*JSONRestClient).doHttp(0xc000143720, 0x19d7560, 0xc0003c2240, 0xc00036c3f0, 0x7, 0x17879e9, 0x9, 0xc0000b2280, 0x0, 0x0, ...)
	/home/rskolasinski/work/seldon-core/executor/api/rest/client.go:168 +0x830
github.com/seldonio/seldon-core/executor/api/rest.(*JSONRestClient).call(0xc000143720, 0x19d7560, 0xc0003c2240, 0xc00036c3f0, 0x7, 0x17879e9, 0x9, 0xc00036c3e0, 0x7, 0x2329, ...)
	/home/rskolasinski/work/seldon-core/executor/api/rest/client.go:228 +0x251
github.com/seldonio/seldon-core/executor/api/rest.(*JSONRestClient).Metadata(0xc000143720, 0x19d7560, 0xc0003c2240, 0xc00036c3f0, 0x7, 0xc00036c3e0, 0x7, 0x2329, 0x0, 0x0, ...)
	/home/rskolasinski/work/seldon-core/executor/api/rest/client.go:238 +0x1c7
github.com/seldonio/seldon-core/executor/predictor.(*PredictorProcess).MetadataMap(0xc0004656a0, 0xc00014ca00, 0xc000314000, 0xc000314000, 0x0)
	/home/rskolasinski/work/seldon-core/executor/predictor/predictor_process.go:335 +0xa6
github.com/seldonio/seldon-core/executor/predictor.NewGraphMetadata(0xc00045b6a0, 0xc0000ee120, 0xa, 0x19e0ec0, 0xc0003e4060)
	/home/rskolasinski/work/seldon-core/executor/predictor/metadata.go:30 +0x3d
github.com/seldonio/seldon-core/executor/api/rest.(*SeldonRestApi).graph_metadata(0xc0000ee360, 0x7fb25c62d380, 0xc0007b4050, 0xc0003cc200)
	/home/rskolasinski/work/seldon-core/executor/api/rest/server.go:364 +0x219
net/http.HandlerFunc.ServeHTTP(0xc000372730, 0x7fb25c62d380, 0xc0007b4050, 0xc0003cc200)
	/usr/lib/go-1.14/src/net/http/server.go:2012 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1(0x19d4520, 0xc0003d6000, 0xc0003cc200)
	/home/rskolasinski/go/pkg/mod/github.com/prometheus/client_golang@v1.3.0/prometheus/promhttp/instrument_server.go:68 +0x11c
net/http.HandlerFunc.ServeHTTP(0xc000479d10, 0x19d4520, 0xc0003d6000, 0xc0003cc200)
	/usr/lib/go-1.14/src/net/http/server.go:2012 +0x44
github.com/seldonio/seldon-core/executor/api/rest.(*CloudeventHeaderMiddleware).Middleware.func1(0x19d4520, 0xc0003d6000, 0xc0003cc200)
	/home/rskolasinski/work/seldon-core/executor/api/rest/server.go:183 +0xd4
net/http.HandlerFunc.ServeHTTP(0xc0003e4000, 0x19d4520, 0xc0003d6000, 0xc0003cc200)
	/usr/lib/go-1.14/src/net/http/server.go:2012 +0x44
github.com/seldonio/seldon-core/executor/api/rest.puidHeader.func1(0x19d4520, 0xc0003d6000, 0xc0003cc200)
	/home/rskolasinski/work/seldon-core/executor/api/rest/server.go:198 +0x111
net/http.HandlerFunc.ServeHTTP(0xc0003e4020, 0x19d4520, 0xc0003d6000, 0xc0003cc200)
	/usr/lib/go-1.14/src/net/http/server.go:2012 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001fc000, 0x19d4520, 0xc0003d6000, 0xc0003cc000)
	/home/rskolasinski/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
net/http.serverHandler.ServeHTTP(0xc0001f42a0, 0x19d4520, 0xc0003d6000, 0xc0003cc000)
	/usr/lib/go-1.14/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc0003c4000, 0x19d74a0, 0xc0003c8000)
	/usr/lib/go-1.14/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/usr/lib/go-1.14/src/net/http/server.go:2933 +0x35c
```

**Comment by adriangonz** [comment]
@RafalSkolasinski this path should be tested on the [`test_tracing.py](https://github.com/SeldonIO/seldon-core/blob/master/testing/scripts/test_tracing.py) tests, shouldn't it?

**Comment by RafalSkolasinski** [comment]
@adriangonz This is about just the executor

**Comment by RafalSkolasinski** [comment]
It seems that would have to run tests in [server_test.go](https://github.com/SeldonIO/seldon-core/blob/master/executor/api/rest/server_test.go) with `tracing.InitTracing()` from `	"github.com/seldonio/seldon-core/executor/api/tracing"
` both enabled and disabled. 

@glindsell Does Go tests have some equivelent of `pytest.mark.parametrize`?

**Comment by RafalSkolasinski** [comment]
To give a bit more context about it - and make notes from discussion with @glindsell. 

On normal `executor` run, tracing is enabled in https://github.com/SeldonIO/seldon-core/blob/9d5eaa74b8b78b6a316149adf995505864934732/executor/main.go#L219
In other words, `executor` always always runs with tracing. This registers tracing as a global singleton. 

Now, in https://github.com/SeldonIO/seldon-core/blob/9d5eaa74b8b78b6a316149adf995505864934732/executor/api/rest/server.go#L183-L188
we add tracing to context if `opentracing.IsGlobalTracerRegistered` evals to `true`.

The first problem is: it always evals to `true` on normal execution but never when running unit tests. 
Therefore one could accidentally remove that block of code and think that all is good because unit tests passes. Thankfully this will be caught by integration tests.

As a final note, I incorrectly labelled this as `bug` - the issue is purely about improving testing.
Also nothing is currently broken and all things work fine. Would suggest to unpin it from `1.2.0` and set lower priority. @cliveseldon?
/priority p2
