### ISSUE TITLE
SIGSEGV when executor staticly linked and CGO_ENABLED=1

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1941]
In the [PR to add Kafka](https://github.com/SeldonIO/seldon-core/pull/1919) the executor needs to be compiled with CGO_ENABLED=1. This seems to have the side effect that glibc libraries for DNS are used by the cmux library used for http/grpc multiplexing. When run this can cause a SIGSEGV panic. This seems to be a bug in glibc. A solution as suggested [here](https://github.com/golang/go/issues/30310) is to ensure you compile with `-tags netgo`

```
{"level":"info","ts":1592032498.0138369,"logger":"entrypoint","msg":"Hostname unset will use localhost"}
{"level":"info","ts":1592032498.0181658,"logger":"entrypoint","msg":"Starting","worker":1}
{"level":"info","ts":1592032498.0182314,"logger":"entrypoint","msg":"Starting","worker":2}
{"level":"info","ts":1592032498.0182464,"logger":"entrypoint","msg":"Starting","worker":3}
{"level":"info","ts":1592032498.0182528,"logger":"entrypoint","msg":"Starting","worker":4}
{"level":"info","ts":1592032498.018258,"logger":"entrypoint","msg":"Starting","worker":5}
{"level":"info","ts":1592032498.020222,"logger":"entrypoint","msg":"Running grpc server ","port":8000}
{"level":"info","ts":1592032498.0203195,"logger":"entrypoint","msg":"Running http server ","port":8000}
{"level":"info","ts":1592032498.0206006,"logger":"entrypoint","msg":"Setting max message size ","size":2147483647}
{"level":"info","ts":1592032498.0220604,"logger":"SeldonRestApi","msg":"Listening","Address":"0.0.0.0:8000"}
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x47 pc=0x7fe2985e21b9]

runtime stack:
runtime.throw(0x1bf2115, 0x2a)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 73 [syscall]:
runtime.cgocall(0x1498510, 0xc0004ce560, 0xc0000cc168)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0004ce530 sp=0xc0004ce4f8 pc=0x404fcb
net._C2func_getaddrinfo(0xc00061a140, 0x0, 0xc0001e7b30, 0xc0000cc168, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:92 +0x55 fp=0xc0004ce560 sp=0xc0004ce530 pc=0x5ad225
net.cgoLookupIPCNAME.func1(0xc00061a140, 0x33, 0x33, 0xc0001e7b30, 0xc0000cc168, 0x50, 0xc0002440f0, 0xc0004ce648)
	/usr/local/go/src/net/cgo_unix.go:161 +0x13e fp=0xc0004ce5a8 sp=0xc0004ce560 pc=0x5b301e
net.cgoLookupIPCNAME(0x1bbb164, 0x3, 0xc00061a0c0, 0x32, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/cgo_unix.go:161 +0x191 fp=0xc0004ce718 sp=0xc0004ce5a8 pc=0x5ae791
net.cgoIPLookup(0xc0000ce420, 0x1bbb164, 0x3, 0xc00061a0c0, 0x32)
	/usr/local/go/src/net/cgo_unix.go:218 +0x67 fp=0xc0004ce7b8 sp=0xc0004ce718 pc=0x5aeef7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004ce7c0 sp=0xc0004ce7b8 pc=0x45df11
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:228 +0xc7

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fe2985a4160, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0002ec598, 0x72, 0x0, 0x0, 0x1bbe950)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0002ec580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc0002ec580, 0x37e11d600, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0002a4180, 0xc000601c00, 0xc000601c08, 0x28)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0002a4180, 0x1c74648, 0xc0002b6320, 0x1e340c0, 0xc0002e60c8)
	/usr/local/go/src/net/tcpsock.go:261 +0x47
github.com/soheilhy/cmux.(*cMux).Serve(0xc0002b6320, 0x0, 0x0)
	/go/pkg/mod/github.com/soheilhy/cmux@v0.1.4/cmux.go:162 +0xaf
main.main()
	/workspace/cmd/executor/main.go:274 +0xed0

goroutine 19 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2c05900)
	/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd6

goroutine 39 [syscall]:
os/signal.signal_recv(0x45df16)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 41 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0002f9090)
	/go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x57

goroutine 12 [select]:
github.com/seldonio/seldon-core/executor/logger.(*Worker).Start.func1(0xc0003414a0)
	/workspace/logger/worker.go:112 +0x114
created by github.com/seldonio/seldon-core/executor/logger.(*Worker).Start
	/workspace/logger/worker.go:107 +0x3f

goroutine 13 [select]:
github.com/seldonio/seldon-core/executor/logger.(*Worker).Start.func1(0xc000341550)
	/workspace/logger/worker.go:112 +0x114
created by github.com/seldonio/seldon-core/executor/logger.(*Worker).Start
	/workspace/logger/worker.go:107 +0x3f

goroutine 14 [select]:
github.com/seldonio/seldon-core/executor/logger.(*Worker).Start.func1(0xc000341600)
	/workspace/logger/worker.go:112 +0x114
created by github.com/seldonio/seldon-core/executor/logger.(*Worker).Start
	/workspace/logger/worker.go:107 +0x3f

goroutine 15 [select]:
github.com/seldonio/seldon-core/executor/logger.(*Worker).Start.func1(0xc0003416b0)
	/workspace/logger/worker.go:112 +0x114
created by github.com/seldonio/seldon-core/executor/logger.(*Worker).Start
	/workspace/logger/worker.go:107 +0x3f

goroutine 16 [select]:
github.com/seldonio/seldon-core/executor/logger.(*Worker).Start.func1(0xc000341760)
	/workspace/logger/worker.go:112 +0x114
created by github.com/seldonio/seldon-core/executor/logger.(*Worker).Start
	/workspace/logger/worker.go:107 +0x3f

goroutine 66 [chan receive]:
github.com/seldonio/seldon-core/executor/logger.StartDispatcher.func1()
	/workspace/logger/dispatcher.go:23 +0x4d
created by github.com/seldonio/seldon-core/executor/logger.StartDispatcher
	/workspace/logger/dispatcher.go:20 +0x29e

goroutine 67 [select]:
github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollControllerWithTicker(0xc0002bfba0, 0xc00011a050)
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.21.1+incompatible/sampler_remote.go:143 +0xd0
github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollController(0xc0002bfba0)
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.21.1+incompatible/sampler_remote.go:138 +0x80
created by github.com/uber/jaeger-client-go.NewRemotelyControlledSampler
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.21.1+incompatible/sampler_remote.go:85 +0x119

goroutine 69 [select]:
github.com/uber/jaeger-client-go.(*remoteReporter).processQueue(0xc0002f8820)
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.21.1+incompatible/reporter.go:274 +0x120
created by github.com/uber/jaeger-client-go.NewRemoteReporter
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.21.1+incompatible/reporter.go:217 +0x146

goroutine 30 [chan receive]:
github.com/soheilhy/cmux.muxListener.Accept(...)
	/go/pkg/mod/github.com/soheilhy/cmux@v0.1.4/cmux.go:229
google.golang.org/grpc.(*Server).Serve(0xc000384000, 0x1e172a0, 0xc0002a42e0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.0/server.go:621 +0x22e
main.runGrpcServer(0x1e172a0, 0xc0002a42e0, 0x1e29ce0, 0xc00036a5c0, 0xc00034c000, 0x1e3eda0, 0xc0002b6370, 0x1f40, 0xc00010c000, 0x7fff5bb69553, ...)
	/workspace/cmd/executor/main.go:111 +0x25c
created by main.main
	/workspace/cmd/executor/main.go:250 +0xbfe

goroutine 32 [chan receive]:
main.runHttpServer(0x1e172a0, 0xc0002a42c0, 0x1e29ce0, 0xc00036a5c0, 0xc00034c000, 0x1e3ef20, 0xc0002b63c0, 0x1f40, 0xc0002b6300, 0xc00010c000, ...)
	/workspace/cmd/executor/main.go:82 +0x252
created by main.main
	/workspace/cmd/executor/main.go:257 +0xe93

goroutine 71 [IO wait]:
internal/poll.runtime_pollWait(0x7fe2985a4090, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0002ece18, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0002ece00, 0xc0001e7781, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0002ece00, 0xc0001e7781, 0x1, 0x1, 0x2, 0x2, 0x7)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0002e60c8, 0xc0001e7781, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
github.com/soheilhy/cmux.(*bufferedReader).Read(0xc000111040, 0xc0001e7781, 0x1, 0x1, 0x2, 0x2, 0x10c00000007)
	/go/pkg/mod/github.com/soheilhy/cmux@v0.1.4/buffer.go:53 +0x12c
github.com/soheilhy/cmux.(*MuxConn).Read(0xc000111030, 0xc0001e7781, 0x1, 0x1, 0xc00037dd20, 0x2, 0x2)
	/go/pkg/mod/github.com/soheilhy/cmux@v0.1.4/cmux.go:260 +0x4f
net/http.(*connReader).backgroundRead(0xc0001e7770)
	/usr/local/go/src/net/http/server.go:677 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:673 +0xd4

goroutine 52 [chan receive]:
github.com/soheilhy/cmux.muxListener.Accept(...)
	/go/pkg/mod/github.com/soheilhy/cmux@v0.1.4/cmux.go:229
net/http.(*Server).Serve(0xc0003b80e0, 0x1e172a0, 0xc0002a42c0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2896 +0x280
main.runHttpServer.func1(0xc0003b80e0, 0x1e172a0, 0xc0002a42c0, 0x1e29ce0, 0xc00036a5c0)
	/workspace/cmd/executor/main.go:69 +0x43
created by main.runHttpServer
	/workspace/cmd/executor/main.go:68 +0x168

goroutine 72 [select]:
net.cgoLookupIP(0x1e1b120, 0xc0000ef500, 0x1bbb164, 0x3, 0xc00061a0c0, 0x32, 0xc0002e8ea0, 0x1deb0e0, 0xc0002e8ea0, 0x1, ...)
	/usr/local/go/src/net/cgo_unix.go:229 +0x195
net.(*Resolver).lookupIP(0x2c043e0, 0x1e1b120, 0xc0000ef500, 0x1bbb164, 0x3, 0xc00061a0c0, 0x32, 0x8, 0xc0004ce578, 0x50, ...)
	/usr/local/go/src/net/lookup_unix.go:96 +0x18d
net.glob..func1(0x1e1b120, 0xc0000ef500, 0xc000272070, 0x1bbb164, 0x3, 0xc00061a0c0, 0x32, 0x1dda1a0, 0x2c30a60, 0x0, ...)
	/usr/local/go/src/net/hook.go:23 +0x72
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:269 +0x12c
internal/singleflight.(*Group).doCall(0x2c043f0, 0xc000244140, 0xc00061a100, 0x36, 0xc0000ef540)
	/usr/local/go/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2bc

goroutine 70 [select]:
net.(*Resolver).lookupIPAddr(0x2c043e0, 0x1e1b160, 0xc0000bc000, 0x1bbb164, 0x3, 0xc00061a0c0, 0x32, 0x2328, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup.go:275 +0x664
net.(*Resolver).internetAddrList(0x2c043e0, 0x1e1b160, 0xc0000bc000, 0x1bbb164, 0x3, 0xc00061a0c0, 0x37, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:280 +0x605
net.(*Resolver).resolveAddrList(0x2c043e0, 0x1e1b160, 0xc0000bc000, 0x1bbb7f8, 0x4, 0x1bbb164, 0x3, 0xc00061a0c0, 0x37, 0x0, ...)
	/usr/local/go/src/net/dial.go:220 +0x506
net.(*Dialer).DialContext(0xc00042d530, 0x1e1b160, 0xc0000bc000, 0x1bbb164, 0x3, 0xc00061a0c0, 0x37, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:402 +0x1fe
net.(*Dialer).Dial(...)
	/usr/local/go/src/net/dial.go:347
net.Dial(0x1bbb164, 0x3, 0xc00061a0c0, 0x37, 0x2, 0xc00061a0c0, 0x37, 0x10000c00006d678)
	/usr/local/go/src/net/dial.go:318 +0xa8
github.com/seldonio/seldon-core/executor/predictor.Ready(0xc0000e2500, 0x8, 0x10)
	/workspace/predictor/ready_checker.go:17 +0x20c
github.com/seldonio/seldon-core/executor/api/rest.(*SeldonRestApi).checkReady(0xc000326120, 0x1e16760, 0xc000178000, 0xc000314300)
	/workspace/api/rest/server.go:160 +0x37
net/http.HandlerFunc.ServeHTTP(0xc000306130, 0x1e16760, 0xc000178000, 0xc000314300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/seldonio/seldon-core/executor/api/rest.xssMiddleware.func1(0x1e16760, 0xc000178000, 0xc000314300)
	/workspace/api/rest/middlewares.go:61 +0x131
net/http.HandlerFunc.ServeHTTP(0xc00036a1c0, 0x1e16760, 0xc000178000, 0xc000314300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/seldonio/seldon-core/executor/api/rest.(*CloudeventHeaderMiddleware).Middleware.func1(0x1e16760, 0xc000178000, 0xc000314300)
	/workspace/api/rest/middlewares.go:38 +0xd4
net/http.HandlerFunc.ServeHTTP(0xc00036a1e0, 0x1e16760, 0xc000178000, 0xc000314300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/seldonio/seldon-core/executor/api/rest.puidHeader.func1(0x1e16760, 0xc000178000, 0xc000314300)
	/workspace/api/rest/middlewares.go:53 +0x111
net/http.HandlerFunc.ServeHTTP(0xc00036a220, 0x1e16760, 0xc000178000, 0xc000314300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00035c9c0, 0x1e16760, 0xc000178000, 0xc000314100)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
net/http.serverHandler.ServeHTTP(0xc0003b80e0, 0x1e16760, 0xc000178000, 0xc000314100)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0000e2780, 0x1e1b120, 0xc0000eec00)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384

```

**Comment by axsaucedo** [comment]
@cliveseldon I think was resolved on the latest state of the PR, or should we keep open?
