### ISSUE TITLE
Serving local (host) model with the prepackaged TensorFlow server

### ISSUE THREAD

**Issue by artmatsak** [SeldonIO/seldon-core#2146]
For development purposes, I'm looking to serve a TensorFlow model located on my host machine as opposed to having it downloaded from external storage. Here is my deployment file:

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: tfserving
spec:
  name: use-qa
  predictors:
  - graph:
      children: []
      implementation: TENSORFLOW_SERVER
      modelUri: file:///home/amatsak/models/universal-sentence-encoder-qa/3
      name: use-qa-model
      parameters:
        - name: signature_name
          type: STRING
          value: question_encoder
        - name: model_name
          type: STRING
          value: universal-sentence-encoder-qa
    name: default
    replicas: 1
```

The container fails to initialize with the following error:

```
[I 200716 13:23:18 initializer-entrypoint:13] Initializing, args: src_uri [file:///home/amatsak/models/universal-sentence-encoder-qa/3] dest_path[ [/mnt/models]
[I 200716 13:23:18 storage:35] Copying contents of file:///home/amatsak/models/universal-sentence-encoder-qa/3 to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 54, in download
    return Storage._download_local(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 192, in _download_local
    raise RuntimeError("Local path %s does not exist." % (uri))
RuntimeError: Local path file:///home/amatsak/models/universal-sentence-encoder-qa/3 does not exist.
```

If I understand it correctly, I need to mount the model directory on my host as a volume and reference the mounted path in `modelUri`. How do I do that with a prepackaged server please?

**Comment by axsaucedo** [comment]
You could actually follow this example which basically doesn't use the prepackaged servers but still uses the tensorflow protocol, you can then just add your  volume via the container/pod overrides https://docs.seldon.io/projects/seldon-core/en/latest/examples/protocol_examples.html#Tensorflow-Protocol-REST-Model

**Comment by artmatsak** [comment]
That makes sense, thanks!
