### ISSUE TITLE
Python Wrapper should Handle Exceptions correctly

### ISSUE THREAD

**Issue by mwm5945** [SeldonIO/seldon-core#2338]
If an exception were to happen in the python model wrapper, the exception is not handled correctly when using REST. During REST invocation of the wrapper, an exception would result in the following payload: 
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

Logs from Orchestrator:
```
2020-08-27 17:46:39.103 DEBUG 17 --- [         task-2] i.s.e.s.InternalPredictionService        : Requesting http://localhost:9000/predict
2020-08-27 17:46:39.158 ERROR 17 --- [         task-2] i.s.e.s.InternalPredictionService        : Couldn't retrieve prediction from external prediction server -- bad http return code: 500

org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 INTERNAL SERVER ERROR
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:79) ~[spring-web-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125) ~[spring-web-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:785) ~[spring-web-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:743) ~[spring-web-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717) ~[spring-web-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:470) ~[spring-web-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at io.seldon.engine.service.InternalPredictionService.queryREST(InternalPredictionService.java:493) ~[classes!/:1.2.2]
	at io.seldon.engine.service.InternalPredictionService.transformInput(InternalPredictionService.java:291) ~[classes!/:1.2.2]
	at io.seldon.engine.predictors.PredictiveUnitBean.transformInput(PredictiveUnitBean.java:257) ~[classes!/:1.2.2]
	at io.seldon.engine.predictors.PredictiveUnitBean.getOutputAsync(PredictiveUnitBean.java:134) ~[classes!/:1.2.2]
	at io.seldon.engine.predictors.PredictiveUnitBean$$FastClassBySpringCGLIB$$ddb0d27b.invoke(<generated>) ~[classes!/:1.2.2]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

2020-08-27 17:46:39.168 ERROR 17 --- [         task-2] i.s.e.s.InternalPredictionService        : Invalid protocol buffer during Json Format merge -

com.google.protobuf.InvalidProtocolBufferException: Expect message object but got: "<!DOCTYPE"
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1483) ~[protobuf-java-util-3.11.3.jar!/:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1460) ~[protobuf-java-util-3.11.3.jar!/:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1342) ~[protobuf-java-util-3.11.3.jar!/:?]
	at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:477) ~[protobuf-java-util-3.11.3.jar!/:?]
	at io.seldon.engine.service.InternalPredictionService.handleHttpStatusCodeError(InternalPredictionService.java:535) ~[classes!/:1.2.2]
	at io.seldon.engine.service.InternalPredictionService.queryREST(InternalPredictionService.java:517) ~[classes!/:1.2.2]
	at io.seldon.engine.service.InternalPredictionService.transformInput(InternalPredictionService.java:291) ~[classes!/:1.2.2]
	at io.seldon.engine.predictors.PredictiveUnitBean.transformInput(PredictiveUnitBean.java:257) ~[classes!/:1.2.2]
	at io.seldon.engine.predictors.PredictiveUnitBean.getOutputAsync(PredictiveUnitBean.java:134) ~[classes!/:1.2.2]
	at io.seldon.engine.predictors.PredictiveUnitBean$$FastClassBySpringCGLIB$$ddb0d27b.invoke(<generated>) ~[classes!/:1.2.2]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

2020-08-27 17:46:39.172 ERROR 17 --- [ault-executor-0] i.g.i.SerializingExecutor                : Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@4d48b542

java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-29.0-jre.jar!/:?]
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209) ~[grpc-core-1.25.0.jar!/:1.25.0]
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202) ~[grpc-core-1.25.0.jar!/:1.25.0]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:371) ~[grpc-stub-1.25.0.jar!/:1.25.0]
	at io.seldon.engine.grpc.SeldonService.predict(SeldonService.java:57) ~[classes!/:1.2.2]
	at io.seldon.protos.SeldonGrpc$MethodHandlers.invoke(SeldonGrpc.java:415) ~[classes!/:1.2.2]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) ~[grpc-stub-1.25.0.jar!/:1.25.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) ~[grpc-core-1.25.0.jar!/:1.25.0]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) ~[grpc-core-1.25.0.jar!/:1.25.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.25.0.jar!/:1.25.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.25.0.jar!/:1.25.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Obviously, the Engine/Executor cannot convert this into a Seldon Message, so a different error is returned. Invoking the orchestrator via GRPC yields the following Error:
```
 rpc error: code = Unknown desc =   
```
Via REST:
``` json
{
  "status": {
    "code": 203,
    "info": "com.google.protobuf.InvalidProtocolBufferException: Expect message object but got: \"\u003c!DOCTYPE\"",
    "reason": "Microservice error",
    "status": "FAILURE"
  }
}
```
I wonder if wrapping the REST api's in a `try`/`except` block, and returning the status code with the body as a Seldon Message would be the solution? -->
https://github.com/SeldonIO/seldon-core/blob/4eb029e3d4a8d242058a6d6544494779f0b5716b/python/seldon_core/wrapper.py#L58

If the model itself is set to GRPC, everything works fine--the appropriate error message is in the response if invoking the orchestrator either via REST or GRPC.

**Comment by cliveseldon** [comment]
Can you provide some more details on the request and SeldonDeployment you are running?
Can you also provide the stack trace on the python wrapper?
Can you reiterate why you are using the Java engine (from slack conversation)?

**Comment by mwm5945** [comment]
Request:
``` json
{"data":{"names":["a", "b"], "ndarray":[[10, 100]]}}
```
 
SDEP:
``` yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
    name: test-model-1
  name: test-model-1
spec:
  annotations:
    deployment_version: "1"
    project_name: test model
    prometheus.io/scrape: "false"
    seldon.io/engine-java-opts: -XX:+UseG1GC -XX:MaxRAMPercentage=75.0
    seldon.io/grpc-max-message-size: "5100000"
    seldon.io/grpc-read-timeout: "100000"
    seldon.io/rest-connection-timeout: "100000"
    seldon.io/rest-read-timeout: "100000"
  name: test-model-1
  predictors:
  - annotations:
      maas_lob: test
      maas_model_name: model
      maas_model_version: "1"
    componentSpecs:
    - hpaSpec:
        maxReplicas: 5
        metrics:
        - resource:
            name: cpu
            targetAverageUtilization: 75
          type: Resource
        minReplicas: 1
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: API_TYPE
            value: REST
          image: [docker image]
          imagePullPolicy: IfNotPresent
          name: node0
          ports:
          - containerPort: 6000
            name: metrics
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 3Gi
            requests:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
          - mountPath: /etc/podinfo
            name: seldon-podinfo
        terminationGracePeriodSeconds: 20
    engineResources: {}
    graph:
      endpoint:
        service_host: localhost
        service_port: 9000
        type: REST
      implementation: UNKNOWN_IMPLEMENTATION
      name: node0
      type: MODEL
    name: test-model-0
    replicas: 1
    svcOrchSpec:
      resources:
        limits:
          cpu: "2"
          memory: 3Gi
        requests:
          cpu: 200m
          memory: 1Gi
```
Model Logs:
```
2020-09-03 13:00:59,281 - ModelMain:predict:28 - INFO:  predict called
2020-09-03 13:00:59,281 - ModelMain:predict:29 - INFO:  x: [[ 10 100]]
2020-09-03 13:00:59,282 - ModelMain:predict:30 - INFO:  type: <class 'numpy.ndarray'>
2020-09-03 13:00:59,282 - ModelMain:predict:42 - INFO:  caught an exception: internal model error: Traceback (most recent call last):
  File "/app/ModelMain.py", line 36, in predict
    m = meta['doesnt exist']
KeyError: 'doesnt exist'

2020-09-03 13:00:59,283 - seldon_core.wrapper:log_exception:1892 - ERROR:  Exception on /predict [POST]
Traceback (most recent call last):
  File "/app/ModelMain.py", line 36, in predict
    m = meta['doesnt exist']
KeyError: 'doesnt exist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/seldon_core/wrapper.py", line 59, in Predict
    user_model, requestJson, seldon_metrics
  File "/usr/local/lib/python3.7/dist-packages/seldon_core/seldon_methods.py", line 108, in predict
    user_model, features, class_names, meta=meta
  File "/usr/local/lib/python3.7/dist-packages/seldon_core/user_model.py", line 209, in client_predict
    return user_model.predict(features, feature_names, **kwargs)
  File "/app/ModelMain.py", line 43, in predict
    raise Exception(err)
Exception: internal model error: Traceback (most recent call last):
  File "/app/ModelMain.py", line 36, in predict
    m = meta['doesnt exist']
KeyError: 'doesnt exist'

127.0.0.1 - - [03/Sep/2020:13:00:59 +0000] "POST /predict HTTP/1.1" 500 290 "-" "Apache-HttpClient/4.5.10 (Java/11.0.7)"
```

Predict Fn:
``` python
    def predict(self, X, feature_names, meta):
            logger.info("predict called")
            logger.info("type: %s", type(X))

            # Cause an exception
            logger.info("meta: %s", meta)
            m = meta['doesnt exist']

            return X
        except Exception as e:
            err = "internal model error: " + traceback.format_exc()
            logger.info("caught an exception: %s", err)
            raise Exception(err)
```

We're using the Java engine over the Executor as the version we're running of Seldon (v1.2.2) doesn't play nicely with setting up the ports with Istio. We'll gladly switch over to the Executor once that is fixed, though i suspect the Executor would have the same problem.

**Comment by cliveseldon** [comment]
The ports issue will be fixed in 1.3.
Can you test this on the executor?

**Comment by mwm5945** [comment]
@cliveseldon Same issue with the executor, logs from the model look the same. Executor log:
```
{"level":"info","ts":1599840958.8921173,"logger":"JSONRestClient","msg":"httpPost failed","response code":500}
```
Response from Executor:
```
\u003c!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"\u003e
\u003ctitle\u003e500 Internal Server Error\u003c/title\u003e
\u003ch1\u003eInternal Server Error\u003c/h1\u003e
\u003cp\u003eThe server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.\u003c/p\u003e
```
