### ISSUE TITLE
DNS error in API Gateway for old deployments gRPC

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#262]
Does mot cause any issues but might be waste of resources as the gRPC Channel seems to be left even after deployment is removed.

```
2018-10-18 14:41:36.226  WARN 5 --- [ault-executor-0] io.grpc.internal.ManagedChannelImpl      : [io.grpc.internal.ManagedChannelImpl-9] Failed to resolve name. status=Status{code=UNAVAILABLE, description=null, cause=java.net.UnknownHostException: myabtest: Name does not resolve
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at io.grpc.internal.DnsNameResolver$JdkResolver.resolve(DnsNameResolver.java:325)
	at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:156)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
}
```

**Comment by cliveseldon** [comment]
Closing as stale.
