### ISSUE TITLE
Custom metrics endpoint produces exceptions during load-testing

### ISSUE THREAD

**Issue by anggao** [SeldonIO/seldon-core#2704]
## Describe the bug

We are doing a load-testing with Seldon-core v1.4, and got the following exception

```
[bbml-all-features] [2020-11-24 19:42:38,391] [22] [ERROR] app.py:log_exception:1892 Exception on /prometheus [GET] [MainThread]
Traceback (most recent call last):
  File "/miniconda/envs/model_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/miniconda/envs/model_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/miniconda/envs/model_env/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/miniconda/envs/model_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/miniconda/envs/model_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/miniconda/envs/model_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/miniconda/envs/model_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/miniconda/envs/model_env/lib/python3.7/site-packages/seldon_core/wrapper.py", line 166, in Metrics
    metrics, mimetype = seldon_metrics.generate_metrics()
  File "/miniconda/envs/model_env/lib/python3.7/site-packages/seldon_core/metrics.py", line 185, in generate_metrics
    exposition.generate_latest(myregistry).decode("utf-8"),
  File "/miniconda/envs/model_env/lib/python3.7/site-packages/prometheus_client/exposition.py", line 106, in generate_latest
    for metric in registry.collect():
  File "/miniconda/envs/model_env/lib/python3.7/site-packages/prometheus_client/registry.py", line 82, in collect
    for metric in collector.collect():
  File "/miniconda/envs/model_env/lib/python3.7/site-packages/seldon_core/metrics.py", line 159, in collect
    with self._lock:
  File "/miniconda/envs/model_env/lib/python3.7/multiprocessing/managers.py", line 1053, in __enter__
    return self._callmethod('acquire')
  File "/miniconda/envs/model_env/lib/python3.7/multiprocessing/managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "/miniconda/envs/model_env/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/miniconda/envs/model_env/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/miniconda/envs/model_env/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
```

sample response 

```
{
    "meta": {
        "metrics": [
            {
                "type": "TIMER",
                "key": "data_fetch_time",
                "value": 0,
                "tags": {
                    "seldon_wrapper": "0.9.1",
                    "run_id": "f2f4282b958541069c22f33caa2ef970"
                }
            },
            {
                "type": "TIMER",
                "key": "predict_time",
                "value": 9,
                "tags": {
                    "seldon_wrapper": "0.9.1",
                    "run_id": "f2f4282b958541069c22f33caa2ef970"
                }
            }
        ],
        "puid": "unset"
    },
    "data": {
        "names": [
            "id",
            "score"
        ],
        "ndarray": [
```

The model service initially works fine, but after a while we start seeing these exceptions and the model stops to predict.

## To reproduce

Run a load-testing for model with custom metrics

## Expected behaviour

Custom metrics endpoint should still works fine under load-testing.

## Environment

Seldon-Core v.1.4 Python module
Seldon-Core v1.4 Operator
Seldon-Core v1.4 go Executor

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by anggao** [comment]
@axsaucedo FYI

**Comment by cliveseldon** [comment]
One also for @RafalSkolasinski

**Comment by anggao** [comment]
@cliveseldon @axsaucedo  @RafalSkolasinski  Thank you!
After a bit more testing, this looks like our config issue, we are using the old memory setting for the model, looks like the new python module needs more memory, as the metrics are stored in the model container after upgrade.
I will close the issue.
