### ISSUE TITLE
Permission denied while creating directory by model

### ISSUE THREAD

**Issue by pnutmath** [SeldonIO/seldon-core#3204]
## Describe the bug
I have created Tensorflow Recommender model with https://www.tensorflow.org/recommenders/examples/quickstart guide

## To reproduce
**Run code locally:** Works
**Created builder image:** Works
````shell
s2i build . seldonio/seldon-core-s2i-python3:1.7.0 tfre:latest -e MODEL_NAME=tfre -e SERVICE_TYPE=MODEL -e PERSISTENCE=0
````
**Deploy the model using seldon:**
````yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: tfre-model
spec:
  name: tfre
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: tensorflow-re
          image: tfre:latest
    graph:
      children: []
      endpoint:
        type: REST
      name: tensorflow-re
      type: MODEL
    name: default
    replicas: 1
````

## Expected behaviour
My model should have access to create directory in pod

## Environment
Kubernetes Cluster in EKS
Seldon core installed with Ambassador

* Cloud Provider: AWS EKS
#### Kubernetes version:
 ````
 Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"} 
````

#### Seldon Images:
          value: docker.io/seldonio/engine:1.7.0
          value: docker.io/seldonio/seldon-core-executor:1.7.0
        image: docker.io/seldonio/seldon-core-operator:1.7.0

## Model Details 
* Images of your model: 
````json
{"apiVersion":"machinelearning.seldon.io/v1alpha2","kind":"SeldonDeployment","metadata":{"annotations":{},"name":"tfre-model","namespace":"seldon"},"spec":{"name":"tfre","predictors":[{"componentSpecs":[{"spec":{"containers":[{"image":"tfre:latest","name":"tensorflow-re"}]}}],"graph":{"children":[],"endpoint":{"type":"REST"},"name":"tensorflow-re","type":"MODEL"},"name":"default","replicas":1}]}}
````
* Logs of your model: 
````logs
2021-05-17 14:22:39.072185: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-17 14:22:39.072218: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-17 14:22:40,309 - seldon_core.microservice:main:203 - INFO:  Starting microservice.py:main
2021-05-17 14:22:40,309 - seldon_core.microservice:main:204 - INFO:  Seldon Core version: 1.7.0
2021-05-17 14:22:40,310 - seldon_core.microservice:main:332 - INFO:  Parse JAEGER_EXTRA_TAGS []
2021-05-17 14:22:40,310 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation cni.projectcalico.org/podIP:192.168.39.165/32 
2021-05-17 14:22:40,310 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation cni.projectcalico.org/podIPs:192.168.39.165/32 
2021-05-17 14:22:40,310 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation kubernetes.io/config.seen:2021-05-17T14:21:00.783093015Z 
2021-05-17 14:22:40,310 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation kubernetes.io/config.source:api 
2021-05-17 14:22:40,310 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation kubernetes.io/psp:eks.privileged 
2021-05-17 14:22:40,310 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation prometheus.io/path:/prometheus 
2021-05-17 14:22:40,310 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation prometheus.io/scrape:true 
2021-05-17 14:22:40,311 - seldon_core.microservice:main:335 - INFO:  Annotations: {'cni.projectcalico.org/podIP': '192.168.39.165/32', 'cni.projectcalico.org/podIPs': '192.168.39.165/32', 'kubernetes.io/config.seen': '2021-05-17T14:21:00.783093015Z', 'kubernetes.io/config.source': 'api', 'kubernetes.io/psp': 'eks.privileged', 'prometheus.io/path': '/prometheus', 'prometheus.io/scrape': 'true'}
2021-05-17 14:22:40,311 - seldon_core.microservice:main:339 - INFO:  Importing tfre
2021-05-17 14:22:40.525445: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
2021-05-17 14:22:41,603 - absl:initialize_from_bucket:453 - INFO:  Load pre-computed DatasetInfo (eg: splits, num examples,...) from GCS: movielens/100k-ratings/0.1.0
2021-05-17 14:22:42,803 - absl:read_from_directory:365 - INFO:  Load dataset info from /tmp/tmpmotn7l83tfds
2021-05-17 14:22:42,804 - absl:read_from_directory:424 - INFO:  Field info.config_name from disk and from code do not match. Keeping the one from code.
2021-05-17 14:22:42,805 - absl:read_from_directory:424 - INFO:  Field info.config_description from disk and from code do not match. Keeping the one from code.
2021-05-17 14:22:42,805 - absl:read_from_directory:424 - INFO:  Field info.module_name from disk and from code do not match. Keeping the one from code.
2021-05-17 14:22:42,805 - absl:download_and_prepare:400 - INFO:  Generating dataset movielens (/microservice/tensorflow_datasets/movielens/100k-ratings/0.1.0)
Downloading and preparing dataset 4.70 MiB (download: 4.70 MiB, generated: 32.41 MiB, total: 37.10 MiB) to /microservice/tensorflow_datasets/movielens/100k-ratings/0.1.0...
Traceback (most recent call last):
  File "/opt/conda/bin/seldon-core-microservice", line 33, in <module>
    sys.exit(load_entry_point('seldon-core', 'console_scripts', 'seldon-core-microservice')())
  File "/microservice/python/seldon_core/microservice.py", line 340, in main
    interface_file = importlib.import_module(args.interface_name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/microservice/tfre.py", line 2, in <module>
    from quick import result
  File "/microservice/quick.py", line 11, in <module>
    data_dir='/microservice/tensorflow_datasets')
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/load.py", line 333, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 415, in download_and_prepare
    download_config=download_config,
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 846, in _make_download_manager
    dataset_name=self.name,
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 217, in __init__
    self._download_dir.mkdir(parents=True, exist_ok=True)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/utils/gpath.py", line 132, in mkdir
    tf.io.gfile.makedirs(self._path_str)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 514, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.PermissionDeniedError: /microservice/tensorflow_datasets; Permission denied
````

**Comment by cliveseldon** [comment]
The container will be not running as root by default. 
https://github.com/SeldonIO/seldon-core/blob/72c30b8910b21eb2c4d7dd02d0ade12a8023b9ea/helm-charts/seldon-core-operator/values.yaml#L40

It depends in that image what the folder permissions are. You may need to set the user for this container as appropriate.

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
