### ISSUE TITLE
Help: Unable to run any standard demos on GKE cluster

### ISSUE THREAD

**Issue by philwinder** [SeldonIO/seldon-core#3305]
## Describe the bug

Whenever running any standard Seldon-core demo (example below) on GKE, with an artefact location of gs://..., the `classifier-model-initializer` fails to download the artefact with a 412 HTTP error.

This is related to, and probably a duplicate of https://github.com/kubeflow/kfserving/issues/762

## Error Logs

```
[I 210617 08:11:43 initializer-entrypoint:13] Initializing, args: src_uri [gs://seldon-models/sklearn/iris] dest_path[ [/mnt/models]
[I 210617 08:11:43 storage:35] Copying contents of gs://seldon-models/sklearn/iris to local
[I 210617 08:11:44 storage:111] Downloading: /mnt/models/metadata.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 951, in download_to_file
    transport, file_obj, download_url, headers, start, end, raw_download
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 834, in _do_download
    download.consume(transport)
  File "/usr/local/lib/python3.7/site-packages/google/resumable_media/requests/download.py", line 153, in consume
    self._process_response(result)
  File "/usr/local/lib/python3.7/site-packages/google/resumable_media/_download.py", line 171, in _process_response
    response, _ACCEPTABLE_STATUS_CODES, self._get_status_code
  File "/usr/local/lib/python3.7/site-packages/google/resumable_media/_helpers.py", line 96, in require_status_code
    *status_codes
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 412, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 48, in download
    Storage._download_gcs(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 112, in _download_gcs
    blob.download_to_filename(dest_path)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1024, in download_to_filename
    if_metageneration_not_match=if_metageneration_not_match,
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 954, in download_to_file
    _raise_from_invalid_response(exc)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 3091, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.PreconditionFailed: 412 GET https://storage.googleapis.com/download/storage/v1/b/seldon-models/o/sklearn%2Firis%2Fmetadata.yaml?generation=1587399258936804&alt=media: ('Request failed with status code', 412, 'Expected one of', <HTTPStatus.OK
```

## To reproduce

1. Install istio and Seldon Core on GKE.
2. Use a standard demo, for example:

```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: iris-model
  namespace: seldon
spec:
  name: iris
  predictors:
  - graph:
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/iris
      name: classifier
    name: default
    replicas: 1
```

## Environment

* Cloud Provider: GKE

#### Kubernetes version:
 Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:10:45Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.6-gke.1000", GitCommit:"3ae0998c5052f420a17cb96bacf860ec5d6822a3", GitTreeState:"clean", BuildDate:"2021-04-29T09:17:16Z", GoVersion:"go1.15.10b5", Compiler:"gc", Platform:"linux/amd64"}

#### Seldon Images:
          value: docker.io/seldonio/engine:1.7.0
          value: docker.io/seldonio/seldon-core-executor:1.7.0
        image: docker.io/seldonio/seldon-core-operator:1.7.0

**Comment by RafalSkolasinski** [comment]
Hi @philwinder,

Could you try with Seldon Core 1.8 or 1.9? We made a move to new, rclone-based storage initializer.

**Comment by RafalSkolasinski** [comment]
Hi @philwinder, 

I just deployed Seldon Core 1.7.0 to GKE cluster and cannot replicate the issue. Everything works fine for me.
```
seldon-core	seldon-system	1       	2021-06-18 10:58:04.285282601 +0100 BST	deployed	seldon-core-operator-1.7.0	           
```

```
λ kubectl logs -n seldon sklearn-iris-default-0-classifier-689c74d4b8-9xcv9 classifier-model-initializer
[I 210618 09:59:46 initializer-entrypoint:13] Initializing, args: src_uri [gs://seldon-models/sklearn/iris] dest_path[ [/mnt/models]
[I 210618 09:59:46 storage:35] Copying contents of gs://seldon-models/sklearn/iris to local
[I 210618 09:59:46 storage:111] Downloading: /mnt/models/metadata.yaml
[I 210618 09:59:47 storage:111] Downloading: /mnt/models/model.joblib
[I 210618 09:59:47 storage:60] Successfully copied gs://seldon-models/sklearn/iris to /mnt/models
```

```
sible-test-default-pool-b2ad735f-s8nw
  Normal  Pulling    3m12s  kubelet            Pulling image "gcr.io/kfserving/storage-initializer:v0.4.0"
  Normal  Pulled     3m6s   kubelet            Successfully pulled image "gcr.io/kfserving/storage-initializer:v0.4.0" in 6.132805913s
  Normal  Created    3m3s   kubelet            Created container classifier-model-initializer
  Normal  Started    3m3s   kubelet            Started container classifier-model-initializer
  Normal  Pulling    3m     kubelet            Pulling image "seldonio/sklearnserver:1.7.0"
  Normal  Pulled     2m39s  kubelet            Successfully pulled image "seldonio/sklearnserver:1.7.0" in 20.984653984s
  Normal  Created    2m29s  kubelet            Created container classifier
  Normal  Started    2m29s  kubelet            Started container classifier
  Normal  Pulling    2m29s  kubelet            Pulling image "docker.io/seldonio/seldon-core-executor:1.7.0"
  Normal  Pulled     2m25s  kubelet            Successfully pulled image "docker.io/seldonio/seldon-core-executor:1.7.0" in 3.969162123s
  Normal  Created    2m25s  kubelet            Created container seldon-container-engine
  Normal  Started    2m25s  kubelet            Started container seldon-container-engine
```

**Comment by philwinder** [comment]
Hi @RafalSkolasinski. Thanks for testing. Yes, you were right. I tested with `1.9.0` and it worked out of the box. Thank you!
