### ISSUE TITLE
 Can't pickle local object 'main.<locals>.grpc_prediction_server'

### ISSUE THREAD

**Issue by minhdang241** [SeldonIO/seldon-core#3410]
## Describe the bug

I have follow the tutorial [here](https://docs.seldon.io/projects/seldon-core/en/stable/python/developer_notes.html) and got the error as 
```
2021-07-16 13:45:27,155 - seldon_core.microservice:main:203 - INFO:  Starting microservice.py:main
2021-07-16 13:45:27,155 - seldon_core.microservice:main:204 - INFO:  Seldon Core version: 1.9.1
2021-07-16 13:45:27,159 - seldon_core.microservice:main:345 - INFO:  Parse JAEGER_EXTRA_TAGS []
2021-07-16 13:45:27,160 - seldon_core.microservice:main:348 - INFO:  Annotations: {}
2021-07-16 13:45:27,160 - seldon_core.microservice:main:352 - INFO:  Importing MyModel
2021-07-16 13:45:28,526 - seldon_core.microservice:main:396 - INFO:  REST microservice running on port 9000 single-threaded=0
2021-07-16 13:45:28,526 - seldon_core.microservice:main:486 - INFO:  REST metrics microservice running on port 6000
2021-07-16 13:45:28,527 - seldon_core.microservice:main:496 - INFO:  Starting servers
Traceback (most recent call last):
  File "/Users/minhdang/opt/miniconda3/envs/datascience/bin/seldon-core-microservice", line 8, in <module>
    sys.exit(main())
  File "/Users/minhdang/opt/miniconda3/envs/datascience/lib/python3.9/site-packages/seldon_core/microservice.py", line 497, in main
    start_servers(server1_func, server2_func, server3_func, metrics_server_func)
  File "/Users/minhdang/opt/miniconda3/envs/datascience/lib/python3.9/site-packages/seldon_core/microservice.py", line 64, in start_servers
    p2.start()
  File "/Users/minhdang/opt/miniconda3/envs/datascience/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/minhdang/opt/miniconda3/envs/datascience/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/minhdang/opt/miniconda3/envs/datascience/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/minhdang/opt/miniconda3/envs/datascience/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/minhdang/opt/miniconda3/envs/datascience/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/minhdang/opt/miniconda3/envs/datascience/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/minhdang/opt/miniconda3/envs/datascience/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.grpc_prediction_server'
```
## Environment

OS: MacOS
Python version: 3.9.5
<!-- You Can fill it manually or paste the output of the command below:

**Comment by cliveseldon** [comment]
Are you using python 3.8 see #1230

**Comment by damosuzuki** [comment]
FYI: Reading the linked issue, it seems that Python 3.8 support has been merged, but I am still facing the same error reported above on 3.8.5.

**Comment by cliveseldon** [comment]
Thanks @damosuzuki can you give any further insight into the issue?

**Comment by damosuzuki** [comment]
Not sure I have more insight, but I can be more verbose :) 

I am trying to follow the same instructions as @minhdang241 (https://docs.seldon.io/projects/seldon-core/en/v1.1.0/python/python_component.html), and I receive the same error when trying to start the example model with `seldon-core-microservice`. I noticed that #1230 adds support for Python 3.8, but I am not sure if this impacts `seldon-core-microservice`.

**Comment by damosuzuki** [comment]
I see now that `seldon-core-microservice` is used in s2i which is now on Python 3.8 by default. I wonder if this is a MacOS specific issue.

**Comment by cliveseldon** [comment]
Please reopen if still an issue on MacOS

**Comment by kfleischmann** [comment]
Have the same problem. Can i support to debug this issue?

**Comment by cliveseldon** [comment]
Thanks. Do you have any further logs or insights here @kfleischmann

**Comment by jeremy-london** [comment]
Hitting this error on Python 3.9.9 using MacOS Big Sur 11.6.2

```
2022-01-19 11:05:30,987 - seldon_core.microservice:main:567 - INFO:  Starting servers
Traceback (most recent call last):
  File "/Users/e346901/Projects/Gitlab/dai/radlab/irad/mlops-irad/workspaces/s92-nlp/env/bin/seldon-core-microservice", line 8, in <module>
    sys.exit(main())
  File "/Users/e346901/Projects/Gitlab/dai/radlab/irad/mlops-irad/workspaces/s92-nlp/env/lib/python3.9/site-packages/seldon_core/microservice.py", line 568, in main
    start_servers(server1_func, server2_func, server3_func, metrics_server_func)
  File "/Users/e346901/Projects/Gitlab/dai/radlab/irad/mlops-irad/workspaces/s92-nlp/env/lib/python3.9/site-packages/seldon_core/microservice.py", line 72, in start_servers
    p2.start()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.grpc_prediction_server'
```

**Comment by simanto604newscred** [comment]
Facing same with 3.9

**Comment by RuiLi-5413** [comment]
Same error with 3.8.6

**Comment by gerilya** [comment]
It looks like it's related to the way multiprocessing is implemented on MacOs and is the same issue as reported here: https://github.com/pydoit/doit/issues/372

I've checked the [PR which resolves](https://github.com/pydoit/doit/pull/368) it and modified `microservice.py` as follows:
Replaced the following line:
`import multiprocess as mp`
With the following lines:
```
try:
        import multiprocess as mp
        HAS_MULTIPROCESS = True
except ImportError:
        import multiprocessing as mp
```
That fixed the issue for me. I have `multiprocess                 0.70.12.2` installed.

**Comment by cliveseldon** [comment]
This is great - thanks @gerilya - we can include this in the next release @RafalSkolasinski
