### ISSUE TITLE
Cloud Pickle Protocol issue with MLflow Model Registry

### ISSUE THREAD

**Issue by jvschoen** [SeldonIO/seldon-core#3461]
When registering a model using MLflow Model Registry from Databricks, and try to deploy to Seldon core we receive the following error:

```
Traceback (most recent call last):
  File "/opt/conda/bin/seldon-core-microservice", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/seldon_core/microservice.py", line 362, in main
    user_object = user_class(**parameters)
  File "/microservice/MyModel.py", line 25, in __init__
    model_uri=f"models:/{account_profile_model_name}/{account_profile_model_version}"
  File "/opt/conda/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 481, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/opt/conda/lib/python3.7/site-packages/mlflow/pyfunc/model.py", line 223, in _load_pyfunc
    python_model = cloudpickle.load(f)
ValueError: unsupported pickle protocol: 5
```

When including `pickle5` to the requirements.txt the Image Pull errors out. The `pickle5` package is supposed to help with backwards compatibility with `cloudpickle`.

According to Databricks the runtime we are using (8.4 ML) is using cloud pickle protocol 4, so not sure why the deployed environment thinks it is reading pickle protocol 5.

@kmlamkin can provide some further details about the kubernetes manifest if needed.

**Comment by jvschoen** [comment]
Error Code when including `pickle5` to the requirements.txt:
```
Error from server (BadRequest): container "my-model-all-accounts" in pod "seldon-1539a2cfdb9b4b101e68a022c9635ddf-5566f4bd8b-87rf7" is waiting to start: trying and failing to pull image
```

**Comment by cliveseldon** [comment]
Could you verify the pickle version? e.g. https://stackoverflow.com/questions/19807790/given-a-pickle-dump-in-python-how-to-i-determine-the-used-protocol

**Comment by jvschoen** [comment]
With Databricks not supporting python 3.7 in their runtimes anymore, do you have plans to upgrade Seldon to handle python 3.8+?

What do you mean by checking pickle version? The error log above shows that `cloudpickle` is trying to unpickle protocol 5

**Comment by cliveseldon** [comment]
On python 3.8: yes: https://github.com/SeldonIO/seldon-core/issues/3500

**Comment by cliveseldon** [comment]
Are you able to test the latest update we have for MLFlow models as outlined here: https://docs.seldon.io/projects/seldon-core/en/latest/servers/mlflow.html?highlight=mlflow#v2-kfserving-protocol-incubating ?

It would be good to see if this method using our MLServer project works for you as this is the direction we are heading.

**Comment by jvschoen** [comment]
To respond to your earlier request I ran this code chunk:
```python
import pickle
import pickletools

data = {'key': 'value'}
with open('temp.pkl', 'wb') as f:
    pickle.dump(data, f)
    
with open('temp.pkl', 'rb') as f:
    proto = None
    op, fst, snd = next(pickletools.genops(f))
    if op.name == 'PROTO':
        proto = fst

print(proto)
```
The output showed 4 being the used protocol. I am using the Databricks 9.0ML runtime.

**Comment by kmlamkin9** [comment]
@cliveseldon We are using seldon core's custom image and running the object on kubernetes using the Seldon Core Operator. Not using kfserving. Since kfserving is still in an incubator period, we don't want to use it for production workloads. Here is what we have for container creation and container deployment:

`s2i build -E environment . seldonio/seldon-core-s2i-python37-ubi8:${S2I_IMAGE_VERSION} ${IMAGE_BASE}:${VERSION}
`

`apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: inference-graph
spec:
  name: my-model-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: dynamo-step
          image: kmlamkin/dynamo_step:0.3.5

        - name: my-model-all-accounts
          image: kmlamkin/ml_model:0.8.66
          env:
          - name: MLFLOW_TRACKING_URI
            value: "databricks"
          - name: DATABRICKS_HOST
            value: "<host>"
          - name: DATABRICKS_USERNAME
            value: "token"
          - name: DATABRICKS_TOKEN
            value: "<token>"

        serviceAccountName: service-account

    graph:
      name: dynamo-step
      parameters:
      - name: ip_table
        type: STRING
        value: 'ip_table'
      endpoint:
        type: REST
      type: MODEL
      children:
        - name: my-model-all-accounts
          parameters:
          - name: account_profiles_list
            type: STRING
            value: 'trust_modelpython37:1'
          endpoint:
            type: REST
          type: MODEL
          children: []

    name: inference-graph
    replicas: 1
`

**Comment by cliveseldon** [comment]
can you test with `seldonio/seldon-core-s2i-python38:1.10.0` instead?

**Comment by RafalSkolasinski** [comment]
Apologies, I have missed the notification. 

In MLFlow Server, I believe there would be a new environment created for the inference based on the `conda.yaml` associated with the deployed model?

**Comment by cliveseldon** [comment]
We are looking in future API updates to allow more configurable and clearer requirements for environments for your models to ensure the correct server image is created. Can you provide some feedback on what would be ideal for you?
