### ISSUE TITLE
Seldon Go Executor test suite doesn't pass

### ISSUE THREAD

**Issue by vikulaggarwal** [SeldonIO/seldon-core#3644]
On running the tests for Seldon Go Executor, the test suite fails.

## To reproduce
1. Git clone the seldon-core repo.
2. Go to the directory for executor module.
3. Run the tests. I used `make -f Makefile docker-build`

## Expected behaviour
The tests should pass

Following is a stacktrace for the tests failure:

```
(⎈ |oci-qac-cp:framework-core)➜  executor git:(db2bc0695) ✗ make -f Makefile docker-build
rm -rf _operator
cp -r ../operator _operator
go fmt ./api/... ./predictor/... ./k8s/... ./logger/...
go vet ./api/... ./predictor/... ./k8s/... ./logger/...
go test ./api/... ./predictor/... ./k8s/... ./logger/... -coverprofile cover.out
?   	github.com/seldonio/seldon-core/executor/api	[no test files]
?   	github.com/seldonio/seldon-core/executor/api/client	[no test files]
ok  	github.com/seldonio/seldon-core/executor/api/grpc	1.571s	coverage: 18.0% of statements
?   	github.com/seldonio/seldon-core/executor/api/grpc/kfserving	[no test files]
?   	github.com/seldonio/seldon-core/executor/api/grpc/kfserving/inference	[no test files]
--- FAIL: TestClientPredict (0.13s)
    client_test.go:74: Started
    client_test.go:86: 
        Expected
            <*status.Error | 0xc0001a64e8>: {
                e: {
                    state: {
                        NoUnkeyedLiterals: {},
                        DoNotCompare: [],
                        DoNotCopy: [],
                        atomicMessageInfo: {
                            GoReflectType: <*reflect.rtype | 0x55c1540>{size: 0x8, ptrdata: 0x8, hash: 2058361438, tflag: 9, align: 8, fieldAlign: 8, kind: 54, equal: 0x4004d20, gcdata: 1, str: 103188, ptrToThis: 0},
                            Desc: <*filedesc.Message | 0xc000222270>{
                                Base: {
                                    L0: {
                                        FullName: "google.rpc.Status",
                                        ParentFile: {
                                            fileRaw: {
                                                builder: {GoPackagePath: ..., RawDescriptor: ..., NumEnums: ..., NumMessages: ..., NumExtensions: ..., NumServices: ..., TypeResolver: ..., FileRegistry: ...},
                                                allEnums: [],
                                                allMessages: [...],
                                                allExtensions: [],
                                                allServices: [],
                                            },
                                            L1: {
                                                Syntax: 3,
                                                Path: "google/rpc/status.proto",
                                                Package: "google.rpc",
                                                Enums: {List: ..., once: ..., byName: ...},
                                                Messages: {List: ..., once: ..., byName: ...},
                                                Extensions: {List: ..., once: ..., byName: ...},
                                                Services: {List: ..., once: ..., byName: ...},
                                            },
                                            once: 1,
                                            mu: {state: 0, sema: 0},
                                            L2: {
                                                Options: 0x41b86c0,
                                                Imports: [...],
                                                Locations: {List: ..., File: ..., once: ..., byPath: ...},
                                            },
                                        },
                                        Parent: <*filedesc.File | 0xc0001f2700>{
                                            fileRaw: {
                                                builder: {GoPackagePath: ..., RawDescriptor: ..., NumEnums: ..., NumMessages: ..., NumExtensions: ..., NumServices: ..., TypeResolver: ..., FileRegistry: ...},
                                                allEnums: [],
                                                allMessages: [...],
                                                allExtensions: [],
                                                allServices: [],
                                            },
                                            L1: {
                                                Syntax: 3,
                                                Path: "google/rpc/status.proto",
                                                Package: "google.rpc",
                                                Enums: {List: ..., once: ..., byName: ...},
                                                Messages: {List: ..., once: ..., byName: ...},
                                                Extensions: {List: ..., once: ..., byName: ...},
                                                Services: {List: ..., once: ..., byName: ...},
                                            },
                                            once: 1,
                                            mu: {state: 0, sema: 0},
                                            L2: {
                                                Options: 0x41b86c0,
                                                Imports: [...],
                                                Locations: {List: ..., File: ..., once: ..., byPath: ...},
                                            },
                                        },
                                        Index: 0,
                                    },
                                },
                                L1: {
                                    Enums: {
         ...
        
        Gomega truncated this representation as it exceeds 'format.MaxLength'.
        Consider having the object provide a custom 'GomegaStringer' representation
        or adjust the parameters in Gomega's 'format' package.
        
        Learn more here: https://onsi.github.io/gomega/#adjusting-output
        
        to be nil
--- FAIL: TestClientPredictTimeout (0.09s)
    client_test.go:91: Started
    client_test.go:103: 
        Expected
            <string>: "...de = Unavai..."
        to equal               |
            <string>: "...de = Deadli..."
--- FAIL: TestClientPredictMessageSize (0.09s)
    client_test.go:107: Started
    client_test.go:119: 
        Expected
            <string>: "...de = Unavai..."
        to equal               |
            <string>: "...de = Resour..."
--- FAIL: TestClientMetadata (0.09s)
    client_test.go:123: Started
panic: interface conversion: interface {} is *proto.SeldonMessage, not *proto.SeldonModelMetadata [recovered]
	panic: interface conversion: interface {} is *proto.SeldonMessage, not *proto.SeldonModelMetadata

goroutine 114 [running]:
testing.tRunner.func1.2(0x550f6e0, 0xc00009d470)
	/usr/local/Cellar/go@1.16/1.16.8/libexec/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000102a80)
	/usr/local/Cellar/go@1.16/1.16.8/libexec/src/testing/testing.go:1146 +0x4b6
panic(0x550f6e0, 0xc00009d470)
	/usr/local/Cellar/go@1.16/1.16.8/libexec/src/runtime/panic.go:965 +0x1b9
github.com/seldonio/seldon-core/executor/api/grpc/seldon.TestClientMetadata(0xc000102a80)
	/Users/vikulaggarwal/Documents/Projects/seldon-core/executor/api/grpc/seldon/client_test.go:132 +0x5d9
testing.tRunner(0xc000102a80, 0x579c540)
	/usr/local/Cellar/go@1.16/1.16.8/libexec/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/Cellar/go@1.16/1.16.8/libexec/src/testing/testing.go:1238 +0x2b3
FAIL	github.com/seldonio/seldon-core/executor/api/grpc/seldon	1.010s
?   	github.com/seldonio/seldon-core/executor/api/grpc/seldon/proto	[no test files]
?   	github.com/seldonio/seldon-core/executor/api/grpc/seldon/test	[no test files]
ok  	github.com/seldonio/seldon-core/executor/api/grpc/tensorflow	1.017s	coverage: 19.0% of statements
ok  	github.com/seldonio/seldon-core/executor/api/kafka	0.858s	coverage: 1.2% of statements
ok  	github.com/seldonio/seldon-core/executor/api/metric	1.076s	coverage: 26.7% of statements
ok  	github.com/seldonio/seldon-core/executor/api/payload	1.118s	coverage: 56.2% of statements
ok  	github.com/seldonio/seldon-core/executor/api/rest	1.666s	coverage: 62.2% of statements
?   	github.com/seldonio/seldon-core/executor/api/test	[no test files]
ok  	github.com/seldonio/seldon-core/executor/api/tracing	1.201s	coverage: 72.2% of statements
ok  	github.com/seldonio/seldon-core/executor/api/util	1.069s	coverage: 38.0% of statements
ok  	github.com/seldonio/seldon-core/executor/predictor	0.744s	coverage: 70.5% of statements
ok  	github.com/seldonio/seldon-core/executor/k8s	0.387s	coverage: 72.7% of statements
?   	github.com/seldonio/seldon-core/executor/logger	[no test files]
FAIL
make: *** [test] Error 1
```

## Environment
I am running the tests on MacOS. The operator tests pass. I have done the required kubebuilder setup. I am using Go version go1.16.8 darwin/amd64

**Comment by axsaucedo** [comment]
This is not something that we have come across before so we currently don't have a list of ports and permissions - have you tried running these tests using the `act` tool as suggested in slack? Conscious we run these tests on every PR not sure what we'd be able to provide if we can't reproduce on our side

**Comment by cliveseldon** [comment]
Please reopen if still an issue
