### ISSUE TITLE
Mistyped check causing NULL Pointer Exceptions with getNamespace

### ISSUE THREAD

**Issue by ro7m** [SeldonIO/seldon-core#367]
@cliveseldon 
Mistyped check causing NULL Pointer Exceptions with getNamespace
PR to resolve this : https://github.com/SeldonIO/seldon-core/pull/366

```

2019-01-06 12:59:19.725 ERROR 1 --- [pool-1-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
--
  |  
  | java.lang.NullPointerException: null
  | at io.seldon.clustermanager.k8s.SeldonDeploymentWatcher.getNamespace(SeldonDeploymentWatcher.java:130) ~[classes!/:0.2.5]
  | at io.seldon.clustermanager.k8s.SeldonDeploymentWatcher.watchSeldonMLDeployments(SeldonDeploymentWatcher.java:200) ~[classes!/:0.2.5]
  | at io.seldon.clustermanager.k8s.SeldonDeploymentWatcher.watch(SeldonDeploymentWatcher.java:226) ~[classes!/:0.2.5]
  | at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[na:na]
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
  | at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
  | at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.20.RELEASE.jar!/:4.3.20.RELEASE]
  | at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.20.RELEASE.jar!/:4.3.20.RELEASE]
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
  | at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_181]
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_181]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]


```

**Comment by ro7m** [comment]
resolved with #366
