### ISSUE TITLE
Error to build env:  Command 'conda run -n mlflow pip install -r /microservice/requirements.txt' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by dvrybak** [SeldonIO/seldon-core#3670]
## Describe the bug

Hello!
We use  Seldon core to deploy Mlflow model, which is logged in MlFlow tracker version 1.20.3.
Model - pytorch python flavour

Seldon builds conda environment for serving model and get error during python requirements installation:
```
ERROR: Command errored out with exit status 1: /opt/conda/envs/mlflow/bin/python3.8 /opt/conda/envs/mlflow/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpqa244jgg Check the logs for full command output.
```

## Expected behaviour

A running model.

## Environment
seldon-core-operator-1.10.0, installed by helm
in kubernetes 1.22.4 (baremetal)
mlmodel logged with MlFlow tracker version 1.20.3
default image for MLFLOW - {"defaultImageVersion":"1.10.0","image":"seldonio/mlflowserver"}}}

## Model Details 
Our seldon deployment file:
```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: mlflow-model
spec:
  name: mlflow
  predictors:
  - graph:
      implementation: MLFLOW_SERVER
      modelUri: s3://mlflow/11/05278c34f55d4afdb54f3b36e0f0fc9b/artifacts/model/
      envSecretRefName: seldon-rclone-secret
      name: classifier
    name: default
    replicas: 1
```

Logs

```
Executing before-run script
---> Creating environment with Conda...
INFO:root:Copying contents of /mnt/models to local
INFO:root:Reading MLmodel file
INFO:root:Creating Conda environment 'mlflow' from conda.yaml
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done


Downloading and Extracting Packages
libgomp-11.2.0 | 425 KB | | 0% libgomp-11.2.0 | 425 KB | 3 | 4% libgomp-11.2.0 | 425 KB | ########## | 100% libgomp-11.2.0 | 425 KB | ########## | 100%
libffi-3.3 | 51 KB | | 0% libffi-3.3 | 51 KB | ########## | 100%
libstdcxx-ng-11.2.0 | 4.2 MB | | 0% libstdcxx-ng-11.2.0 | 4.2 MB | 7 | 7% libstdcxx-ng-11.2.0 | 4.2 MB | ######2 | 62% libstdcxx-ng-11.2.0 | 4.2 MB | #########7 | 97% libstdcxx-ng-11.2.0 | 4.2 MB | ########## | 100%
readline-8.1 | 295 KB | | 0% readline-8.1 | 295 KB | ########## | 100% readline-8.1 | 295 KB | ########## | 100%
wheel-0.37.0 | 31 KB | | 0% wheel-0.37.0 | 31 KB | ########## | 100%
setuptools-58.2.0 | 1011 KB | | 0% setuptools-58.2.0 | 1011 KB | ########## | 100% setuptools-58.2.0 | 1011 KB | ########## | 100%
ncurses-6.2 | 985 KB | | 0% ncurses-6.2 | 985 KB | ######4 | 65% ncurses-6.2 | 985 KB | ########## | 100%
openssl-1.1.1l | 2.1 MB | | 0% openssl-1.1.1l | 2.1 MB | #####5 | 55% openssl-1.1.1l | 2.1 MB | ########## | 100%
_libgcc_mutex-0.1 | 3 KB | | 0% _libgcc_mutex-0.1 | 3 KB | ########## | 100%
sqlite-3.36.0 | 1.4 MB | | 0% sqlite-3.36.0 | 1.4 MB | ########## | 100% sqlite-3.36.0 | 1.4 MB | ########## | 100%
ld_impl_linux-64-2.3 | 667 KB | | 0% ld_impl_linux-64-2.3 | 667 KB | #6 | 17% ld_impl_linux-64-2.3 | 667 KB | ########## | 100% ld_impl_linux-64-2.3 | 667 KB | ########## | 100%
xz-5.2.5 | 343 KB | | 0% xz-5.2.5 | 343 KB | #########7 | 98% xz-5.2.5 | 343 KB | ########## | 100%
tk-8.6.11 | 3.3 MB | | 0% tk-8.6.11 | 3.3 MB | #2 | 12% tk-8.6.11 | 3.3 MB | ########## | 100% tk-8.6.11 | 3.3 MB | ########## | 100%
ca-certificates-2021 | 139 KB | | 0% ca-certificates-2021 | 139 KB | #########2 | 92% ca-certificates-2021 | 139 KB | ########## | 100%
tzdata-2021c | 120 KB | | 0% tzdata-2021c | 120 KB | #######9 | 80% tzdata-2021c | 120 KB | ########## | 100%
libgcc-ng-11.2.0 | 886 KB | | 0% libgcc-ng-11.2.0 | 886 KB | # | 11% libgcc-ng-11.2.0 | 886 KB | #####6 | 56% libgcc-ng-11.2.0 | 886 KB | ########## | 100% libgcc-ng-11.2.0 | 886 KB | ########## | 100%
zlib-1.2.11 | 86 KB | | 0% zlib-1.2.11 | 86 KB | ########## | 100%
pip-21.3 | 1.2 MB | | 0% pip-21.3 | 1.2 MB | ##7 | 27% pip-21.3 | 1.2 MB | ########## | 100% pip-21.3 | 1.2 MB | ########## | 100%
python_abi-3.9 | 4 KB | | 0% python_abi-3.9 | 4 KB | ########## | 100%
python-3.9.2 | 27.3 MB | | 0% python-3.9.2 | 27.3 MB | 1 | 1% python-3.9.2 | 27.3 MB | # | 10% python-3.9.2 | 27.3 MB | ##6 | 26% python-3.9.2 | 27.3 MB | ####3 | 44% python-3.9.2 | 27.3 MB | ###### | 61% python-3.9.2 | 27.3 MB | #######5 | 75% python-3.9.2 | 27.3 MB | ########9 | 89% python-3.9.2 | 27.3 MB | ########## | 100%
libzlib-1.2.11 | 59 KB | | 0% libzlib-1.2.11 | 59 KB | ########## | 100%
_openmp_mutex-4.5 | 22 KB | | 0% _openmp_mutex-4.5 | 22 KB | ########## | 100% _openmp_mutex-4.5 | 22 KB | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Installing pip dependencies: ...working... Ran pip subprocess with arguments:
['/opt/conda/envs/mlflow/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/tmpc8spee5x/condaenv.1jzx2_cj.requirements.txt']
Pip subprocess output:
Collecting mlflow==1.20.1


... too much logs


Successfully built alembic databricks-cli
Installing collected packages: MarkupSafe, Werkzeug, urllib3, smmap, six, Jinja2, itsdangerous, idna, greenlet, click, charset-normalizer, certifi, zipp, websocket-client, wcwidth, typing-extensions, traitlets, tabulate, sqlalchemy, requests, pytz, python-editor, python-dateutil, pyparsing, ptyprocess, prometheus-client, parso, numpy, Mako, gitdb, Flask, torch, sqlparse, querystring-parser, pyyaml, pygments, protobuf, prompt-toolkit, prometheus-flask-exporter, pillow, pickleshare, pexpect, pandas, packaging, matplotlib-inline, jedi, importlib-metadata, gunicorn, gitpython, entrypoints, docker, decorator, databricks-cli, cloudpickle, backcall, alembic, tqdm, torchvision, mlflow, ipython
Successfully installed Flask-2.0.2 Jinja2-3.0.2 Mako-1.1.5 MarkupSafe-2.0.1 Werkzeug-2.0.2 alembic-1.4.1 backcall-0.2.0 certifi-2021.10.8 charset-normalizer-2.0.7 click-8.0.3 cloudpickle-2.0.0 databricks-cli-0.15.0 decorator-5.1.0 docker-5.0.3 entrypoints-0.3 gitdb-4.0.7 gitpython-3.1.24 greenlet-1.1.2 gunicorn-20.1.0 idna-3.2 importlib-metadata-4.8.1 ipython-7.28.0 itsdangerous-2.0.1 jedi-0.18.0 matplotlib-inline-0.1.3 mlflow-1.20.2 numpy-1.21.2 packaging-21.0 pandas-1.3.3 parso-0.8.2 pexpect-4.8.0 pickleshare-0.7.5 pillow-8.3.2 prometheus-client-0.11.0 prometheus-flask-exporter-0.18.3 prompt-toolkit-3.0.20 protobuf-3.18.1 ptyprocess-0.7.0 pygments-2.10.0 pyparsing-2.4.7 python-dateutil-2.8.2 python-editor-1.0.4 pytz-2021.3 pyyaml-5.4.1 querystring-parser-1.2.4 requests-2.26.0 six-1.16.0 smmap-4.0.0 sqlalchemy-1.4.25 sqlparse-0.4.2 tabulate-0.8.9 torch-1.9.1 torchvision-0.10.1 tqdm-4.62.3 traitlets-5.1.0 typing-extensions-3.10.0.2 urllib3-1.26.7 wcwidth-0.2.5 websocket-client-1.2.1 zipp-3.6.0

done
#
# To activate this environment, use
#
#     $ conda activate mlflow
#
# To deactivate an active environment, use
#
#     $ conda deactivate

INFO:root:Install additional package from requirements.txt
Processing ./python
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

ERROR conda.cli.main_run:execute(34): Subprocess for 'conda run ['pip', 'install', '-r', '/microservice/requirements.txt']' command failed.  (See above for error)
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/envs/mlflow/bin/python3.8 /opt/conda/envs/mlflow/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpqa244jgg
       cwd: /microservice/python
  Complete output (5 lines):
  running egg_info
  creating seldon_core.egg-info
  /tmp/pip-build-env-f3o7ab8x/overlay/lib/python3.8/site-packages/setuptools/dist.py:487: UserWarning: Normalizing '1.12.0-dev' to '1.12.0.dev0'
    warnings.warn(tmpl.format(**locals()))
  error: could not create 'seldon_core.egg-info': Permission denied
  ----------------------------------------
WARNING: Discarding file:///microservice/python. Command errored out with exit status 1: /opt/conda/envs/mlflow/bin/python3.8 /opt/conda/envs/mlflow/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpqa244jgg Check the logs for full command output.
ERROR: Command errored out with exit status 1: /opt/conda/envs/mlflow/bin/python3.8 /opt/conda/envs/mlflow/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpqa244jgg Check the logs for full command output.

Traceback (most recent call last):
  File "./conda_env_create.py", line 151, in <module>
    main(args)
  File "./conda_env_create.py", line 146, in main
    setup_env(model_folder)
  File "./conda_env_create.py", line 55, in setup_env
    install_base_reqs()
  File "./conda_env_create.py", line 136, in install_base_reqs
    run(cmd, shell=True, check=True)
  File "/opt/conda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'conda run -n mlflow pip install -r /microservice/requirements.txt' returned non-zero exit status 1.
```

**Comment by bernardolk** [comment]
We are having the same issue. Not sure how we managed to deploy it once and now, after a memory caused the eviction of the pods, we can't redeploy. We are hours into it without much progress, any help is appreciated.

**Comment by axsaucedo** [comment]
@dvrybak we have added https://github.com/SeldonIO/seldon-core/pull/3674 - can you test?

You can test through the followin steps:

* Build the python wrapper image (ie `make -C wrappers/s2i/python build PYTHON_VERSION=3.7.10`)
* Build the mlflow base image (ie `make -C servers/mlflowserver build`)
* Ensure the mlflow base image is loaded to your kind cluster or update the (values.yaml on SC installation)[https://github.com/SeldonIO/seldon-core/blob/268551d27f44afc829ea6c287188392db291e38e/helm-charts/seldon-core-operator/values.yaml#L116]
* Re-run your mlflow model

Once you can test we can make sure that is the proper fix and merge. Let me know if you have any questions.

**Comment by bernardolk** [comment]
> Hi, @bernardolk
> 
> Create a new docker image with more permissions and add this image to [custom inference servers](https://docs.seldon.io/projects/seldon-core/en/v1.1.0/servers/custom.html).
> 
> ```
> FROM seldonio/mlflowserver:1.10.0
> USER root
> RUN chmod 777 /microservice
> USER 8888
> ```
> 
> And redeploy your models,

Unfortunately, this didn't work.
We are using Seldon helm chart, in that case, how could I test this fix?

**Comment by bernardolk** [comment]
Okay, we fixed it using the fix in the PR above. After providing the correct image, the pods went back up.
We are concerned now though: It seems not that many people are using Seldon + MLflow ? 
Its weird that this bug appeared for us out of nowhere after the models were deployed, what could be the explanation?

**Comment by mohammedi-haroune** [comment]
We're having a similar error, we can't even deploy models that used to work before, the only thing that changed is the version of pip installed by `conda`, it was installing 21.1.3 when it used to work but now it's installing 22.1.4, I fixed the issue by pinning the pip version in the `conda.yaml` file.

So, the bug is introduced by pip 22.1.4 which apparently needs permission to create a "build" directory in "/microservice/python/"
