### ISSUE TITLE
Unable to start almost empty project with seldon-core-microservice on Python 3.8+

### ISSUE THREAD

**Issue by marrrcin** [SeldonIO/seldon-core#3697]
## Describe the bug
I've followed https://docs.seldon.io/projects/seldon-core/en/latest/python/python_wrapping_docker.html to create a simple Python model for Seldon Core using Docker.
 
I cannot launch nearly empty project with seldon-core-microservice due to exception:

`AttributeError: Can't pickle local object 'main.<locals>.grpc_prediction_server'`.

<details>
  <summary markdown="span">Full stack trace</summary>

```
2021-10-22 12:02:44,530 - seldon_core.microservice:main:206 - INFO:  Starting microservice.py:main
2021-10-22 12:02:44,530 - seldon_core.microservice:main:207 - INFO:  Seldon Core version: 1.11.2
2021-10-22 12:02:44,531 - seldon_core.microservice:main:362 - INFO:  Parse JAEGER_EXTRA_TAGS []
2021-10-22 12:02:44,531 - seldon_core.microservice:main:365 - INFO:  Annotations: {}
2021-10-22 12:02:44,531 - seldon_core.microservice:main:369 - INFO:  Importing SeldonTransformer
Traceback (most recent call last):
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/bin/seldon-core-microservice", line 8, in <module>
    sys.exit(main())
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/lib/python3.8/site-packages/seldon_core/microservice.py", line 370, in main
    interface_file = importlib.import_module(args.interface_name)
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'SeldonTransformer'
(seldon-bug-2) ➜  seldon-bug-1 seldon-core-microservice t.SeldonTransformer --service-type=TRANSFORMER
2021-10-22 12:02:51,845 - seldon_core.microservice:main:206 - INFO:  Starting microservice.py:main
2021-10-22 12:02:51,845 - seldon_core.microservice:main:207 - INFO:  Seldon Core version: 1.11.2
2021-10-22 12:02:51,847 - seldon_core.microservice:main:362 - INFO:  Parse JAEGER_EXTRA_TAGS []
2021-10-22 12:02:51,847 - seldon_core.microservice:main:365 - INFO:  Annotations: {}
2021-10-22 12:02:51,848 - seldon_core.microservice:main:373 - INFO:  Importing submodule ['t', 'SeldonTransformer']
Initializing
2021-10-22 12:02:55,648 - seldon_core.microservice:main:448 - INFO:  REST gunicorn microservice running on port 9000
2021-10-22 12:02:55,649 - seldon_core.microservice:main:542 - INFO:  REST metrics microservice running on port 6000
2021-10-22 12:02:55,649 - seldon_core.microservice:main:552 - INFO:  Starting servers
Traceback (most recent call last):
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/bin/seldon-core-microservice", line 8, in <module>
    sys.exit(main())
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/lib/python3.8/site-packages/seldon_core/microservice.py", line 553, in main
    start_servers(server1_func, server2_func, server3_func, metrics_server_func)
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/lib/python3.8/site-packages/seldon_core/microservice.py", line 67, in start_servers
    p2.start()
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/marcin/opt/anaconda3/envs/seldon-bug-2/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.grpc_prediction_server'
```

</details>

## To reproduce
1. `conda create -n seldon-bug python=3.8 -y`
2. `conda activate seldon-bug`
2. `pip install torch tensorflow seldon-core`
3. Create new python file (`asdf.py`) with the following class (note 0 imports there!):
```python
class SeldonTransformer(object):
    def __init__(self):
        print("Initializing")

    def transform_input(self, features, feature_names):
        return features

    def transform_output(self, features, feature_names):
        return features

```
4. Run `seldon-core-microservice asdf.SeldonTransformer --service-type=TRANSFORMER`.

## Expected behaviour
Seldon service starts.

## Additional info
There is no issue on Python 3.7. I see that there is a similar issue related to Python 3.9+ https://github.com/SeldonIO/seldon-core/issues/3410 

## Environment
OS: macOS 11.5.2 Build  20G95
<details>
  <summary markdown="span">Output of <code>pip freeze</code></summary>

```python
absl-py==0.15.0
astunparse==1.6.3
attrs==21.2.0
cachetools==4.2.4
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.7
clang==5.0
click==8.0.3
cryptography==3.4
Flask==1.1.2
Flask-Cors==3.0.10
Flask-OpenTracing==1.1.0
flatbuffers==1.12
gast==0.4.0
google-auth==2.3.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.41.0
grpcio-opentracing==1.1.4
grpcio-reflection==1.34.1
gunicorn==20.1.0
h5py==3.1.0
idna==3.3
itsdangerous==2.0.1
jaeger-client==4.4.0
Jinja2==3.0.2
jsonschema==3.2.0
keras==2.6.0
Keras-Preprocessing==1.1.2
Markdown==3.3.4
MarkupSafe==2.0.1
numpy==1.19.5
oauthlib==3.1.1
opentracing==2.4.0
opt-einsum==3.3.0
prometheus-client==0.8.0
protobuf==3.19.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyrsistent==0.18.0
PyYAML==5.4.1
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.7.2
seldon-core==1.11.2
semantic-version==2.8.5
setuptools-rust==0.12.1
six==1.15.0
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.6.0
tensorflow-estimator==2.6.0
termcolor==1.1.0
threadloop==1.0.2
thrift==0.15.0
toml==0.10.2
torch==1.10.0
tornado==6.1
typing-extensions==3.7.4.3
urllib3==1.25.9
Werkzeug==2.0.2
wrapt==1.12.1

```
</details>

## Model Details 
No model.

**Comment by RafalSkolasinski** [comment]
HI, I cannot reproduce on Linux machine. I am afraid it may be MacOS specific indeed.

I have followed exactly the steps you indicated and it works fine for me.

**Comment by RafalSkolasinski** [comment]
For me the output is 
```
seldon-core-microservice asdf.SeldonTransformer --service-type=TRANSFORMER                                                   (seldon-bug) 
2021-11-01 11:00:22,811 - seldon_core.microservice:main:206 - INFO:  Starting microservice.py:main
2021-11-01 11:00:22,811 - seldon_core.microservice:main:207 - INFO:  Seldon Core version: 1.11.2
2021-11-01 11:00:22,813 - seldon_core.microservice:main:362 - INFO:  Parse JAEGER_EXTRA_TAGS []
2021-11-01 11:00:22,813 - seldon_core.microservice:main:365 - INFO:  Annotations: {}
2021-11-01 11:00:22,813 - seldon_core.microservice:main:373 - INFO:  Importing submodule ['asdf', 'SeldonTransformer']
Initializing
2021-11-01 11:00:22,824 - seldon_core.microservice:main:448 - INFO:  REST gunicorn microservice running on port 9000
2021-11-01 11:00:22,824 - seldon_core.microservice:main:542 - INFO:  REST metrics microservice running on port 6000
2021-11-01 11:00:22,824 - seldon_core.microservice:main:552 - INFO:  Starting servers
2021-11-01 11:00:22,830 - seldon_core.microservice:grpc_prediction_server:504 - INFO:  GRPC Server Binding to '%s' 0.0.0.0:5000 with 1 processes
2021-11-01 11:00:22,833 - seldon_core.wrapper:_set_flask_app_configs:224 - INFO:  App Config:  <Config {'ENV': 'production', 'DEBUG': False, 'TESTING': False, 'PROPAGATE_EXCEPTIONS': None, 'PRESERVE_CONTEXT_ON_EXCEPTION': None, 'SECRET_KEY': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'SEND_FILE_MAX_AGE_DEFAULT': datetime.timedelta(seconds=43200), 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'JSON_AS_ASCII': True, 'JSON_SORT_KEYS': True, 'JSONIFY_PRETTYPRINT_REGULAR': False, 'JSONIFY_MIMETYPE': 'application/json', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093}>
2021-11-01 11:00:22,835 - seldon_core.wrapper:_set_flask_app_configs:224 - INFO:  App Config:  <Config {'ENV': 'production', 'DEBUG': False, 'TESTING': False, 'PROPAGATE_EXCEPTIONS': None, 'PRESERVE_CONTEXT_ON_EXCEPTION': None, 'SECRET_KEY': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'SEND_FILE_MAX_AGE_DEFAULT': datetime.timedelta(seconds=43200), 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'JSON_AS_ASCII': True, 'JSON_SORT_KEYS': True, 'JSONIFY_PRETTYPRINT_REGULAR': False, 'JSONIFY_MIMETYPE': 'application/json', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093}>
2021-11-01 11:00:22,835 - seldon_core.microservice:_run_grpc_server:460 - INFO:  Starting new GRPC server with 1.
[2021-11-01 11:00:22 +0000] [152637] [INFO] Starting gunicorn 20.1.0
[2021-11-01 11:00:22 +0000] [152637] [INFO] Listening at: http://0.0.0.0:6000 (152637)
[2021-11-01 11:00:22 +0000] [152637] [INFO] Using worker: sync
[2021-11-01 11:00:22 +0000] [152647] [INFO] Booting worker with pid: 152647
[2021-11-01 11:00:22 +0000] [152613] [INFO] Starting gunicorn 20.1.0
[2021-11-01 11:00:22 +0000] [152613] [INFO] Listening at: http://0.0.0.0:9000 (152613)
[2021-11-01 11:00:22 +0000] [152613] [INFO] Using worker: sync
[2021-11-01 11:00:22 +0000] [152648] [INFO] Booting worker with pid: 152648
2021-11-01 11:00:22,859 - seldon_core.gunicorn_utils:load:103 - INFO:  Tracing not active
```

Surprising is the difference in import line, I have
```
2021-11-01 11:00:22,813 - seldon_core.microservice:main:373 - INFO:  Importing submodule ['asdf', 'SeldonTransformer']
```

whereas you have 
```
2021-10-22 12:02:44,531 - seldon_core.microservice:main:369 - INFO:  Importing SeldonTransformer
```
and the first error for you is
```
ModuleNotFoundError: No module named 'SeldonTransformer'
```

**Comment by westford14** [comment]
just confirming that i'm seeing this on my Mac as well

following the same steps as above i get: 

* `seldon-core-microservice asdf.SeldonTransformer --service-type=TRANSFORMER` 

```
2021-11-01 10:06:43,599 - seldon_core.microservice:main:206 - INFO:  Starting microservice.py:main
2021-11-01 10:06:43,599 - seldon_core.microservice:main:207 - INFO:  Seldon Core version: 1.11.2
2021-11-01 10:06:43,601 - seldon_core.microservice:main:362 - INFO:  Parse JAEGER_EXTRA_TAGS []
2021-11-01 10:06:43,601 - seldon_core.microservice:main:365 - INFO:  Annotations: {}
2021-11-01 10:06:43,601 - seldon_core.microservice:main:373 - INFO:  Importing submodule ['asdf', 'SeldonTransformer']
Initializing
2021-11-01 10:06:46,272 - seldon_core.microservice:main:448 - INFO:  REST gunicorn microservice running on port 9000
2021-11-01 10:06:46,273 - seldon_core.microservice:main:542 - INFO:  REST metrics microservice running on port 6000
2021-11-01 10:06:46,273 - seldon_core.microservice:main:552 - INFO:  Starting servers
Traceback (most recent call last):
  File "/Users/alee/miniconda3/envs/seldon-bug/bin/seldon-core-microservice", line 8, in <module>
    sys.exit(main())
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/site-packages/seldon_core/microservice.py", line 553, in main
    start_servers(server1_func, server2_func, server3_func, metrics_server_func)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/site-packages/seldon_core/microservice.py", line 67, in start_servers
    p2.start()
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.grpc_prediction_server'
```

my Mac is 11.6

**Comment by RafalSkolasinski** [comment]
seems like similar problem https://github.com/spack/spack/issues/14102 here

**Comment by RafalSkolasinski** [comment]
also https://github.com/browsertron/pytest-parallel/issues/41 and https://bugs.python.org/issue33884

**Comment by RafalSkolasinski** [comment]
Can someone try if adding 
```
import multiprocessing as mp; mp.set_start_method("forkserver")
```
either in your model's file or in `microservice.py` of seldon sovles the problem?

**Comment by RafalSkolasinski** [comment]
Also, could worth checking if running in debug mode also exposes the problem:
```
seldon-core-microservice asdf.SeldonTransformer --service-type=TRANSFORMER --debug
```

**Comment by westford14** [comment]
the multiprocessing import didn't change anything 

* `asdf.py` 

```
import multiprocessing as mp

mp.set_start_method("forkserver")

class SeldonTransformer(object):
    def __init__(self):
        print("Initializing")

    def transform_input(self, features_feature_names):
        return features

    def transform_output(self, features, feature_names):
        return features
```

* `seldon-core-microservice asdf.SeldonTransformer --service-type=TRANSFORMER --debug` 

```
2021-11-01 11:17:03,068 - seldon_core.microservice:main:206 - INFO:  Starting microservice.py:main
2021-11-01 11:17:03,068 - seldon_core.microservice:main:207 - INFO:  Seldon Core version: 1.11.2
2021-11-01 11:17:03,070 - seldon_core.microservice:main:362 - INFO:  Parse JAEGER_EXTRA_TAGS []
2021-11-01 11:17:03,070 - seldon_core.microservice:main:365 - INFO:  Annotations: {}
2021-11-01 11:17:03,070 - seldon_core.microservice:main:373 - INFO:  Importing submodule ['asdf', 'SeldonTransformer']
Initializing
2021-11-01 11:17:06,073 - seldon_core.microservice:main:413 - INFO:  REST microservice running on port 9000 single-threaded=0
2021-11-01 11:17:06,074 - seldon_core.microservice:main:542 - INFO:  REST metrics microservice running on port 6000
2021-11-01 11:17:06,074 - seldon_core.microservice:main:552 - INFO:  Starting servers
Traceback (most recent call last):
  File "/Users/alee/miniconda3/envs/seldon-bug/bin/seldon-core-microservice", line 8, in <module>
    sys.exit(main())
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/site-packages/seldon_core/microservice.py", line 553, in main
    start_servers(server1_func, server2_func, server3_func, metrics_server_func)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/site-packages/seldon_core/microservice.py", line 67, in start_servers
    p2.start()
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/popen_forkserver.py", line 47, in _launch
    reduction.dump(process_obj, buf)
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.grpc_prediction_server'
```

**Comment by RafalSkolasinski** [comment]
Thanks @westford14 - seems it does not help here -worth still check if injecting that into `microservice.py` does the trick.

Would you be able to modify seldon core locally and give it a shot?

**Comment by westford14** [comment]
doesn't seem to help the issue either: 

```
2021-11-01 11:38:54,935 - seldon_core.microservice:main:207 - INFO:  Starting microservice.py:main
2021-11-01 11:38:54,936 - seldon_core.microservice:main:208 - INFO:  Seldon Core version: 1.11.2
2021-11-01 11:38:54,937 - seldon_core.microservice:main:363 - INFO:  Parse JAEGER_EXTRA_TAGS []
2021-11-01 11:38:54,937 - seldon_core.microservice:main:366 - INFO:  Annotations: {}
2021-11-01 11:38:54,937 - seldon_core.microservice:main:374 - INFO:  Importing submodule ['asdf', 'SeldonTransformer']
Traceback (most recent call last):
  File "/Users/alee/miniconda3/envs/seldon-bug/bin/seldon-core-microservice", line 8, in <module>
    sys.exit(main())
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/site-packages/seldon_core/microservice.py", line 375, in main
    interface_file = importlib.import_module(parts[0])
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/alee/Desktop/test/asdf.py", line 3, in <module>
    mp.set_start_method("forkserver")
  File "/Users/alee/miniconda3/envs/seldon-bug/lib/python3.8/multiprocessing/context.py", line 243, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

**Comment by RafalSkolasinski** [comment]
Unfortunately we do not develop on Apple machines so it is difficult for us to even replicate the issue. 
Seldon Core Microservice is meant to be run as a pod in k8s cluster and this works without issue. 

Does this affect you if you try to run in local kind cluster?

**Comment by westford14** [comment]
@RafalSkolasinski nope -- this does not effect this, and totally understood from how this is meant to be run in production. This was just an interesting bug to see pop up.

**Comment by RafalSkolasinski** [comment]
If I ever get my hands onto Apple machine I may have a look but unfortunately chances for this are quite small... 

If you anyone manage to figure it out a solution that would not affect the main use case we will always be happy to accept PRs and merge. 

For now to optimise local development I can only suggest to build docker image and run it locally forwarding corresponding ports
