### ISSUE TITLE
Problems with deploying a model from MLFlow

### ISSUE THREAD

**Issue by kfleischmann** [SeldonIO/seldon-core#3846]
Hey guys. I am trying to deploy the wine example from MLFlow but i still have problems to run the mlflow-server.

Any Idea?

```
│ Executing before-run script                                                                                                                                                                         │
│ ---> Creating environment with Conda...                                                                                                                                                             │
│ INFO:root:Copying contents of /mnt/models to local                                                                                                                                                  │
│ INFO:root:Reading MLmodel file                                                                                                                                                                      │
│ INFO:root:Creating Conda environment 'mlflow' from conda.yaml                                                                                                                                       │
│ Collecting package metadata (repodata.json): ...working... done                                                                                                                                     │
│ Solving environment: ...working... done                                                                                                                                                             │
│ Downloading and Extracting Packages                                                                                                                                                                 │
│ zlib-1.2.11          | 86 KB     |            |   0% zlib-1.2.11          | 86 KB     | ########## | 100% zlib-1.2.11          | 86 KB     | ########## | 100%                                      │
│ ncurses-6.2          | 985 KB    |            |   0% ncurses-6.2          | 985 KB    | ########## | 100% ncurses-6.2          | 985 KB    | ########## | 100%                                      │
│ libgomp-11.2.0       | 427 KB    |            |   0% libgomp-11.2.0       | 427 KB    | ########## | 100% libgomp-11.2.0       | 427 KB    | ########## | 100%                                      │
│ openssl-3.0.0        | 2.9 MB    |            |   0% openssl-3.0.0        | 2.9 MB    | ########## | 100% openssl-3.0.0        | 2.9 MB    | ########## | 100%                                      │
│ wheel-0.37.1         | 31 KB     |            |   0% wheel-0.37.1         | 31 KB     | ########## | 100%                                                                                           │
│ libzlib-1.2.11       | 59 KB     |            |   0% libzlib-1.2.11       | 59 KB     | ########## | 100%                                                                                           │
│ libffi-3.4.2         | 57 KB     |            |   0% libffi-3.4.2         | 57 KB     | ########## | 100%                                                                                           │
│ ld_impl_linux-64-2.3 | 667 KB    |            |   0% ld_impl_linux-64-2.3 | 667 KB    | ########## | 100% ld_impl_linux-64-2.3 | 667 KB    | ########## | 100%                                      │
│ _openmp_mutex-4.5    | 22 KB     |            |   0% _openmp_mutex-4.5    | 22 KB     | ########## | 100%                                                                                           │
│ setuptools-60.5.0    | 1.0 MB    |            |   0% setuptools-60.5.0    | 1.0 MB    | ########## | 100% setuptools-60.5.0    | 1.0 MB    | ########## | 100%                                      │
│ python-3.7.12        | 57.3 MB   |            |   0% python-3.7.12        | 57.3 MB   | 6          |   7% python-3.7.12        | 57.3 MB   | #5         |  16% python-3.7.12        | 57.3 MB   | # │
│ _libgcc_mutex-0.1    | 3 KB      |            |   0% _libgcc_mutex-0.1    | 3 KB      | ########## | 100%                                                                                           │
│ pip-21.3.1           | 1.2 MB    |            |   0% pip-21.3.1           | 1.2 MB    | ##7        |  27% pip-21.3.1           | 1.2 MB    | #########7 |  98% pip-21.3.1           | 1.2 MB    | # │
│ libnsl-2.0.0         | 31 KB     |            |   0% libnsl-2.0.0         | 31 KB     | ########## | 100%                                                                                           │
│ libstdcxx-ng-11.2.0  | 4.2 MB    |            |   0% libstdcxx-ng-11.2.0  | 4.2 MB    | #9         |  19% libstdcxx-ng-11.2.0  | 4.2 MB    | ########## | 100% libstdcxx-ng-11.2.0  | 4.2 MB    | # │
│ tk-8.6.11            | 3.3 MB    |            |   0% tk-8.6.11            | 3.3 MB    | #8         |  19% tk-8.6.11            | 3.3 MB    | ########## | 100% tk-8.6.11            | 3.3 MB    | # │
│ xz-5.2.5             | 343 KB    |            |   0% xz-5.2.5             | 343 KB    | 4          |   5% xz-5.2.5             | 343 KB    | ########## | 100%                                      │
│ sqlite-3.37.0        | 1.5 MB    |            |   0% sqlite-3.37.0        | 1.5 MB    | ########## | 100% sqlite-3.37.0        | 1.5 MB    | ########## | 100%                                      │
│ libgcc-ng-11.2.0     | 887 KB    |            |   0% libgcc-ng-11.2.0     | 887 KB    | ########## | 100% libgcc-ng-11.2.0     | 887 KB    | ########## | 100%                                      │
│ python_abi-3.7       | 4 KB      |            |   0% python_abi-3.7       | 4 KB      | ########## | 100% python_abi-3.7       | 4 KB      | ########## | 100%                                      │
│ readline-8.1         | 295 KB    |            |   0% readline-8.1         | 295 KB    | ########## | 100% readline-8.1         | 295 KB    | ########## | 100%                                      │
│ ca-certificates-2021 | 139 KB    |            |   0% ca-certificates-2021 | 139 KB    | ########## | 100%                                                                                           │
│ Preparing transaction: ...working... done                                                                                                                                                           │
│ Verifying transaction: ...working... done                                                                                                                                                           │
│ Executing transaction: ...working... done                                                                                                                                                           │
│ Installing pip dependencies: ...working... Ran pip subprocess with arguments:                                                                                                                       │
│ ['/opt/conda/envs/mlflow/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/tmp_9vzpnbh/condaenv.2bpqc3l4.requirements.txt']                                                                    │
│ Pip subprocess output:                                                                                                                                                                              │
│ Collecting mlflow                                                                                                                                                                                   │
│   Downloading mlflow-1.22.0-py3-none-any.whl (15.5 MB)                                                                                                                                              │
│ Collecting cloudpickle==2.0.0                                                                                                                                                                       │
│   Downloading cloudpickle-2.0.0-py3-none-any.whl (25 kB)                                                                                                                                            │
│ Collecting psutil==5.8.0                                                                                                                                                                            │
│   Downloading psutil-5.8.0-cp37-cp37m-manylinux2010_x86_64.whl (296 kB)                                                                                                                             │
│ Collecting scikit-learn==1.0.1                                                                                                                                                                      │
│   Downloading scikit_learn-1.0.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (23.2 MB)                                                                                                │
│ Collecting scipy>=1.1.0                                                                                                                                                                             │
│   Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)                                                                                                       │
│ Collecting threadpoolctl>=2.0.0                                                                                                                                                                     │
│   Downloading threadpoolctl-3.0.0-py3-none-any.whl (14 kB)                                                                                                                                          │
│ Collecting joblib>=0.11                                                                                                                                                                             │
│   Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)                                                                                                                                            │
│ Collecting numpy>=1.14.6                                                                                                                                                                            │
│   Downloading numpy-1.21.5-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)                                                                                                      │
│ Collecting protobuf>=3.7.0                                                                                                                                                                          │
│   Downloading protobuf-3.19.3-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)                                                                                                    │
│ Collecting importlib-metadata!=4.7.0,>=3.7.0                                                                                                                                                        │
│   Downloading importlib_metadata-4.10.0-py3-none-any.whl (17 kB)                                                                                                                                    │
│ Collecting entrypoints                                                                                                                                                                              │
│   Downloading entrypoints-0.3-py2.py3-none-any.whl (11 kB)                                                                                                                                          │
│ Collecting requests>=2.17.3                                                                                                                                                                         │
│   Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)                                                                                                                                          │
│ Collecting gunicorn                                                                                                                                                                                 │
│   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)                                                                                                                                              │
│ Collecting pytz                                                                                                                                                                                     │
│   Downloading pytz-2021.3-py2.py3-none-any.whl (503 k
│   Downloading zipp-3.7.0-py3-none-any.whl (5.3 kB)                                                                                                                                                  │
│ Collecting charset-normalizer~=2.0.0                                                                                                                                                                │
│   Downloading charset_normalizer-2.0.10-py3-none-any.whl (39 kB)                                                                                                                                    │
│ Collecting idna<4,>=2.5                                                                                                                                                                             │
│   Downloading idna-3.3-py3-none-any.whl (61 kB)                                                                                                                                                     │
│ Collecting certifi>=2017.4.17                                                                                                                                                                       │
│   Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)                                                                                                                                       │
│ Collecting urllib3<1.27,>=1.21.1                                                                                                                                                                    │
│   Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)                                                                                                                                          │
│ Collecting greenlet!=0.4.17                                                                                                                                                                         │
│   Downloading greenlet-1.1.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (150 kB)                                                                                                     │
│ Collecting itsdangerous>=2.0                                                                                                                                                                        │
│   Downloading itsdangerous-2.0.1-py3-none-any.whl (18 kB)                                                                                                                                           │
│ Collecting Jinja2>=3.0                                                                                                                                                                              │
│   Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB)                                                                                                                                                │
│ Collecting Werkzeug>=2.0                                                                                                                                                                            │
│   Downloading Werkzeug-2.0.2-py3-none-any.whl (288 kB)                                                                                                                                              │
│ Requirement already satisfied: setuptools>=3.0 in /opt/conda/envs/mlflow/lib/python3.7/site-packages (from gunicorn->mlflow->-r /tmp/tmp_9vzpnbh/condaenv.2bpqc3l4.requirements.txt (line 1)) (60.5 │
│ Collecting pyparsing!=3.0.5,>=2.0.2                                                                                                                                                                 │
│   Downloading pyparsing-3.0.6-py3-none-any.whl (97 kB)                                                                                                                                              │
│ Collecting prometheus-client                                                                                                                                                                        │
│   Downloading prometheus_client-0.12.0-py2.py3-none-any.whl (57 kB)                                                                                                                                 │
│ Collecting smmap<6,>=3.0.1                                                                                                                                                                          │
│   Downloading smmap-5.0.0-py3-none-any.whl (24 kB)                                                                                                                                                  │
│ Collecting MarkupSafe>=2.0                                                                                                                                                                          │
│   Downloading MarkupSafe-2.0.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (31 kB)                                                             │
│ Building wheels for collected packages: alembic, databricks-cli                                                                                                                                     │
│   Building wheel for alembic (setup.py): started                                                                                                                                                    │
│   Building wheel for alembic (setup.py): finished with status 'done'                                                                                                                                │
│   Created wheel for alembic: filename=alembic-1.4.1-py2.py3-none-any.whl size=158171 sha256=7ff453a3277e3758a71918b4f9b2b1b800f17b0a6b8217d26b65d8ae0f5ce0e3                                        │
│   Stored in directory: /tmp/pip-ephem-wheel-cache-3y5eehs6/wheels/be/5d/0a/9e13f53f4f5dfb67cd8d245bb7cdffe12f135846f491a283e3                                                                       │
│   Building wheel for databricks-cli (setup.py): started                                                                                                                                             │
│   Building wheel for databricks-cli (setup.py): finished with status 'done'                                                                                                                         │
│   Created wheel for databricks-cli: filename=databricks_cli-0.16.2-py3-none-any.whl size=106811 sha256=ee79a596b1497bad8abb204dcc6837e513b65061482b78e74f8d52e03ea453f3                             │
│   Stored in directory: /tmp/pip-ephem-wheel-cache-3y5eehs6/wheels/f4/5c/ed/e1ce20a53095f63b27b4964abbad03e59cf3472822addf7d29                                                                       │
│ Successfully built alembic databricks-cli                                                                                                                                                           │
│ Installing collected packages: zipp, typing-extensions, MarkupSafe, importlib-metadata, Werkzeug, urllib3, smmap, six, Jinja2, itsdangerous, idna, greenlet, click, charset-normalizer, certifi, we │
│ Successfully installed Flask-2.0.2 Jinja2-3.0.3 Mako-1.1.6 MarkupSafe-2.0.1 Werkzeug-2.0.2 alembic-1.4.1 certifi-2021.10.8 charset-normalizer-2.0.10 click-8.0.3 cloudpickle-2.0.0 databricks-cli-0 │
│ done                                                                                                                                                                                                │
│ /opt/conda/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!                                   │
│   RequestsDependencyWarning)                                                                                                                                                                        │
│ ==> WARNING: A newer version of conda exists. <==                                                                                                                                                   │
│   current version: 4.10.3                                                                                                                                                                           │
│   latest version: 4.11.0                                                                                                                                                                            │
│ Please update conda by running                                                                                                                                                                      │
│     $ conda update -n base -c defaults conda                                                                                                                                                        │
│ #                                                                                                                                                                                                   │
│ # To activate this environment, use                                                                                                                                                                 │
│ #                                                                                                                                                                                                   │
│ #     $ conda activate mlflow                                                                                                                                                                       │
│ #                                                                                                                                                                                                   │
│ # To deactivate an active environment, use                                                                                                                                                          │
│ #                                                                                                                                                                                                   │
│ #     $ conda deactivate                                                                                                                                                                            │
│ INFO:root:Install additional package from requirements.txt
...
Downloading requests-0.6.6.tar.gz (30 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.6.5.tar.gz (30 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.6.4.tar.gz (30 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.6.3.tar.gz (26 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.6.2.tar.gz (26 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.6.1.tar.gz (26 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.6.0.tar.gz (25 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.5.1.tar.gz (23 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.5.0.tar.gz (21 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.4.1.tar.gz (18 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.4.0.tar.gz (17 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.3.4.tar.gz (19 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.3.3.tar.gz (18 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.3.2.tar.gz (15 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.3.1.tar.gz (15 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.3.0.tar.gz (15 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.2.4.tar.gz (13 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'error'                                                                                                                                       │
│   Downloading requests-0.2.3.tar.gz (13 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'done'                                                                                                                                        │
│   Downloading requests-0.2.2.tar.gz (13 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'done'                                                                                                                                        │
│   Downloading requests-0.2.1.tar.gz (12 kB)                                                                                                                                                         │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'done'                                                                                                                                        │
│   Downloading requests-0.2.0.tar.gz (5.5 kB)                                                                                                                                                        │
│   Preparing metadata (setup.py): started                                                                                                                                                            │
│   Preparing metadata (setup.py): finished with status 'done'                                                                                                                                        │
│ INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.                               │
│ INFO: pip is looking at multiple versions of pyyaml to determine which version is compatible with other requirements. This could take a while.                                                      │
│ The conflict is caused by:                                                                                                                                                                          │
│     The user requested requests<2.25.0                                                                                                                                                              │
│     mlflow 1.11.0 depends on requests>=2.17.3                                                                                                                                                       │
│     The user requested requests<2.25.0                                                                                                                                                              │
│     mlflow 1.10.0 depends on requests>=2.17.3
...
```
```
WARNING: Discarding https://files.pythonhosted.org/packages/a8/a6/38b9de830719e4cd62ddf51f240654200658d0315aa9e908eda90ee64879/requests-0.6.5.tar.gz#sha256=bb332c171913c2f57cea805d013601af86a46b9 │
│   ERROR: Command errored out with exit status 1:                                                                                                                                                    │
│    command: /opt/conda/envs/mlflow/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8vim7kk9/requests_1659ba7a5f194990a6506a0b933720e5/setup.py'"'"' │
│        cwd: /tmp/pip-install-8vim7kk9/requests_1659ba7a5f194990a6506a0b933720e5/                                                                                                                    │
│   Complete output (7 lines):                                                                                                                                                                        │
│   Traceback (most recent call last):                                                                                                                                                                │
│     File "<string>", line 1, in <module>                                                                                                                                                            │
│     File "/tmp/pip-install-8vim7kk9/requests_1659ba7a5f194990a6506a0b933720e5/setup.py", line 6, in <module>                                                                                        │
│       import requests                                                                                                                                                                               │
│     File "/tmp/pip-install-8vim7kk9/requests_1659ba7a5f194990a6506a0b933720e5/requests/__init__.py", line 3, in <module>                                                                            │
│       from core import *                                                                                                                                                                            │
│   ModuleNotFoundError: No module named 'core'                                                                                                                                                       │
│   ----------------------------------------                                                                                                                                                          │
│ WARNING: Discarding https://files.pythonhosted.org/packages/97/e0/a2bc7317b13caf227a75c8151b562b62a2e9f5d4ab4ad59694bfdbf5c35c/requests-0.6.4.tar.gz#sha256=151f105506913a6b84f6119400ca94732ec39f5 │
│   ERROR: Command errored out with exit status 1:                                                                                                                                                    │
│    command: /opt/conda/envs/mlflow/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8vim7kk9/requests_885755332c5643a1821ca1159b45cb0f/setup.py'"'"' │
│        cwd: /tmp/pip-install-8vim7kk9/requests_885755332c5643a1821ca1159b45cb0f/                                                                                                                    │
│   Complete output (7 lines):                                                                                                                                                                        │
│   Traceback (most recent call last):                                                                                                                                                                │
│     File "<string>", line 1, in <module>                                                                                                                                                            │
│     File "/tmp/pip-install-8vim7kk9/requests_885755332c5643a1821ca1159b45cb0f/setup.py", line 6, in <module>                                                                                        │
│       import requests                                                                                                                                                                               │
│     File "/tmp/pip-install-8vim7kk9/requests_885755332c5643a1821ca1159b45cb0f/requests/__init__.py", line 3, in <module>                                                                            │
│       from core import *                                                                                                                                                                            │
│   ModuleNotFoundError: No module named 'core'                                                                                                                                                       │
│   ----------------------------------------                                                                                                                                                          │
│ WARNING: Discarding https://files.pythonhosted.org/packages/e1/3f/9235f98536b1393ef8a8e2dbd27273588fc3246000b93b0d763325b2e30c/requests-0.6.3.tar.gz#sha256=bde3e2ea45f6e47acd24ff55628fc7325cacd75 │
│   ERROR: Command errored out with exit status 1:                                                                                                                                                    │
│    command: /opt/conda/envs/mlflow/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8vim7kk9/requests_2757267875794d018a5924dbad06fcff/setup.py'"'"' │
│        cwd: /tmp/pip-install-8vim7kk9/requests_2757267875794d018a5924dbad06fcff/                                                                                                                    │
│   Complete output (7 lines):                                                                                                                                                                        │
│   Traceback (most recent call last):                                                                                                                                                                │
│     File "<string>", line 1, in <module>                                                                                                                                                            │
│     File "/tmp/pip-install-8vim7kk9/requests_2757267875794d018a5924dbad06fcff/setup.py", line 6, in <module>                                                                                        │
│       import requests                                                                                                                                                                               │
│     File "/tmp/pip-install-8vim7kk9/requests_2757267875794d018a5924dbad06fcff/requests/__init__.py", line 3, in <module>                                                                            │
│       from core import *                                                                                                                                                                            │
│   ModuleNotFoundError: No module named 'core'                                                                                                                                                       │
│   ----------------------------------------                                                                                                                                                          │
│ WARNING: Discarding https://files.pythonhosted.org/packages/55/19/986305b95fae17c58c95e191943a282bce19f82535af4530890c483937ad/requests-0.6.2.tar.gz#sha256=b5419f909fc21b8eb037dc4bade29530c289936 │
│   ERROR: Command errored out with exit status 1:                                                                                                                                                    │
│    command: /opt/conda/envs/mlflow/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8vim7kk9/requests_de6a4f582aa54a99addbb8a7f4623515/setup.py'"'"' │
│        cwd: /tmp/pip-install-8vim7kk9/requests_de6a4f582aa54a99addbb8a7f4623515/                                                                                                                    │
│   Complete output (7 lines):                                                                                                                                                                        │
│   Traceback (most recent call last):                                                                                                                                                                │
│     File "<string>", line 1, in <module>                                                                                                                                                            │
│     File "/tmp/pip-install-8vim7kk9/requests_de6a4f582aa54a99addbb8a7f4623515/setup.py", line 6, in <module>                                                                                        │
│       import requests                                                                                                                                                                               │
│     File "/tmp/pip-install-8vim7kk9/requests_de6a4f582aa54a99addbb8a7f4623515/requests/__init__.py", line 3, in <module>                                                                            │
│       from core import *                                                                                                                                                                            │
│   ModuleNotFoundError: No module named 'core'                                                                                                                                                       │
│   ----------------------------------------                                                                                                                                                          │
│ WARNING: Discarding https://files.pythonhosted.org/packages/a6/1f/f948fb7ba68b69b13a1fbbb70d7706e889c7b7d3e9867b498ca7971126db/requests-0.6.1.tar.gz#sha256=2656b23db25398e990e6f5d75dfbd960454a1fe │
│   ERROR: Command errored out with exit status 1:                                                                                                                                                    │
│    command: /opt/conda/envs/mlflow/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8vim7kk9/requests_73c7897415a34c6fa25765fdf68f0c62/setup.py'"'"' │
│        cwd: /tmp/pip-install-8vim7kk9/requests_73c7897415a34c6fa25765fdf68f0c62/                                                                                                                    │
│   Complete output (7 lines):                                                                                                                                                                        │
│   Traceback (most recent call last):                                                                                                                                                                │
│     File "<string>", line 1, in <module>                                                                                                                                                            │
│     File "/tmp/pip-install-8vim7kk9/requests_73c7897415a34c6fa25765fdf68f0c62/setup.py", line 6, in <module>                                                                                        │
│       import requests                                                                                                                                                                               │
│     File "/tmp/pip-install-8vim7kk9/requests_73c7897415a34c6fa25765fdf68f0c62/requests/__init__.py", line 3, in <module>                                                                            │
│       from core import *                                                                                                                                                                            │
│   ModuleNotFoundError: No module named 'core'                                                                                                                                                       │
│   ----------------------------------------                                                                                                                                                          │
│ WARNING: Discarding https://files.pythonhosted.org/packages/0b/b8/932de3bc1b8630357de85bc0c794ee1a7d343cb8008b470a0c9d15e84341/requests-0.6.0.tar.gz#sha256=2c5036387b75dfb0ff3971604bd1e691cf6a55d │
│   ERROR: Command errored out with exit status 1:                                                                                                                                                    │
│    command: /opt/conda/envs/mlflow/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8vim7kk9/requests_77a0f16ac63b495884653e67a1c61868/setup.py'"'"' │
│        cwd: /tmp/pip-install-8vim7kk9/requests_77a0f16ac63b495884653e67a1c61868/                                                                                                                    │
│   Complete output (7 lines):
```

**Comment by kfleischmann** [comment]
Is there a possibility that the mlflow server is not the latest? How is it possible to update to the latest version?

**Comment by cliveseldon** [comment]
Can you confirm the version of seldon-core being run?

Any ideas @adriangonz

**Comment by kfleischmann** [comment]
seldon-core	seldon-system	1       	2022-01-06 16:09:44.692056 +0100 CET	deployed	seldon-core-operator-1.12.0	1.12.0

**Comment by adriangonz** [comment]
Hey @kfleischmann , it seems that something else is asking for a version of the `requests` packages incompatible with MLflow itself:

```
The user requested requests<2.25.0
```

Do you know what could be causing this? Is there any chance that something on your `conda.yaml` is asking for this version?

**Comment by adriangonz** [comment]
Just as an update on the above, I just realised that the `requirements.txt` built into the MLflow server image seems to be the one limiting the version of `requests`. We'll bump that one, and hopefully that should do the trick.

**Comment by kfleischmann** [comment]
Okay, so when do you expect i can test it?

**Comment by kfleischmann** [comment]
So, i am also confused with "mlflow<1.12.0" - so i think we should use the latest mlflow version like 1.23 ?
