### ISSUE TITLE
gRPC tensorproto, TypeError

### ISSUE THREAD

**Issue by sathiez** [SeldonIO/seldon-core#410]
I get this error  when I use tensorproto, 
**Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/grpc/_server.py", line 389, in _call_behavior
return behavior(argument, context), True
File "/usr/local/lib/python3.6/site-packages/seldon_core/model_microservice.py", line 169, in Predict
predictions, class_names, default_data_type)
File "/usr/local/lib/python3.6/site-packages/seldon_core/microservice.py", line 215, in array_to_grpc_datadef
ndarray=array_to_list_value(array)
File "/usr/local/lib/python3.6/site-packages/seldon_core/microservice.py", line 102, in array_to_list_value
for sub_array in array:
TypeError: iteration over a 0-d array**

My code is,
#where arr.shape = (480, 640, 3)
arr = tf.make_tensor_proto(arr)
datadef = prediction_pb2.DefaultData(tftensor = arr)
request = prediction_pb2.SeldonMessage(data = datadef)

How can I solve it?

**Comment by cliveseldon** [comment]
The trace suggest you are sending a `ndarray` as if you look at line 214 in microservice.py
https://github.com/SeldonIO/seldon-core/blob/714fa9812e722b8d62982293d133c114be3d2ab3/python/seldon_core/microservice.py#L214

**Comment by cliveseldon** [comment]
Please reopen if still valid.
