### ISSUE TITLE
ModelUri is None when parameters specified in the SeldonDeployment

### ISSUE THREAD

**Issue by Shivdutta** [SeldonIO/seldon-core#4125]
getting the same error in steps graph deployment
Old bug 838
`apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
name: graph-metadata-two-levels
spec:
name: test-deployment
predictors:

    componentSpecs:
        spec:
        containers:
            image: seldonio/sklearnserver:1.13.1
            name: node-one
            image: k3d-myregistry.localhost:12345/shiv/mymodel:v1
            name: node-two
            graph:
            name: node-one
            type: MODEL
            implementation: SKLEARN_SERVER
            modelUri: s3://mlflow/12345612345612345612345612345612/artifacts/model/
            envSecretRefName: seldon-init-container-secret
            name: classifier
            parameters:
            name: method
            type: STRING
            value: predict
            children:
            name: node-two
            type: MODEL
            children: []
            name: example
            replicas: 1
            `

node one is sklearn server
node two is custom model

(base) shivdutta@aiwlaptp041:~/Documents/k3d$ kubectl get pods
NAME READY STATUS RESTARTS AGE
seldon-6f407027272e1028c8e7d1e48c5533f3-6ff8ccd576-6x6fn 3/4 CrashLoopBackOff 7 15m

(base) shivdutta@aiwlaptp041:/Documents/k3d$ kubectl logs -f seldon-6f407027272e1028c8e7d1e48c5533f3-6ff8ccd576-6x6fn -c node-one
/opt/conda/lib/python3.7/site-packages/requests/init.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
RequestsDependencyWarning)
starting microservice
2022-05-27 11:19:20,861 - seldon_core.microservice:main:211 - INFO: Starting microservice.py:main
2022-05-27 11:19:20,861 - seldon_core.microservice:main:212 - INFO: Seldon Core version: 1.13.1
2022-05-27 11:19:20,863 - seldon_core.microservice:main:367 - INFO: Parse JAEGER_EXTRA_TAGS []
2022-05-27 11:19:20,863 - seldon_core.microservice:main:370 - INFO: Annotations: {}
2022-05-27 11:19:20,863 - seldon_core.microservice:main:374 - INFO: Importing SKLearnServer
2022-05-27 11:19:20,891 - SKLearnServer:init:21 - INFO: Model uri: None
2022-05-27 11:19:20,891 - SKLearnServer:init:22 - INFO: method: predict_proba
2022-05-27 11:19:20,891 - SKLearnServer:load:26 - INFO: load
2022-05-27 11:19:20,891 - root:download:31 - INFO: Copying contents of None to local
Traceback (most recent call last):
File "/opt/conda/bin/seldon-core-microservice", line 8, in
sys.exit(main())
File "/opt/conda/lib/python3.7/site-packages/seldon_core/microservice.py", line 384, in main
user_object = user_class(**parameters)
File "/microservice/SKLearnServer.py", line 23, in init
self.load()
File "/microservice/SKLearnServer.py", line 28, in load
seldon_core.Storage.download(self.model_uri), JOBLIB_FILE
File "/opt/conda/lib/python3.7/site-packages/seldon_core/storage.py", line 34, in download
if uri.startswith(_LOCAL_PREFIX) or os.path.exists(uri):
AttributeError: 'NoneType' object has no attribute 'startswith'
(base) shivdutta@aiwlaptp041:/Documents/k3d$

Seldon version Seldon Core version: 1.13.1

**Comment by axsaucedo** [comment]
@Shivdutta it seems the indentation got changed when sharing the logs, would you be able to update the files and logs with the correct indentation and code blocks?
