### ISSUE TITLE
Seldon Core Triton Inference on kubeflow Pipelines deployment issue

### ISSUE THREAD

**Issue by SwathiAunooru** [SeldonIO/seldon-core#4379]
## Imports
```
import kfp
from kfp.components import func_to_container_op
from kfp import dsl
import yaml
from kubernetes import client as k8s
from subprocess import run
```
## Function for deploy

```
def deploy_k8_pod(namespace_pod):
  print("Container")
  import yaml
  from kubernetes import client, config, utils
  from kubernetes.client.rest import ApiException
  from subprocess import run

  # Generate this object from your config file in local machine
  
  v1 = client.CustomObjectsApi()
  config.load_incluster_config()
    

  model_yaml=f"""apiVersion: machinelearning.seldon.io/v1
  kind: SeldonDeployment
  metadata:
    name: rul2
  spec:
    serverType : kafka
    predictors:
    - componentSpecs:
      - spec:
          containers:
          - name: rulnorm
            image: ' '
            env:
              - name: TRANSFORMERS_CACHE
                value: /opt/mlserver/.cache
              - name: MLSERVER_MODEL_NAME 
                value: "rul2"
            resources:
              requests:
                nvidia.com/gpu: 1
              limits:
                nvidia.com/gpu: 1
      graph:
        name: rulnorm
        type: MODEL
        endpoint:
          type: REST        
        children:
          - name: rul2
            implementation: TRITON_SERVER
            modelUri: gs://....
      name: default
      svcOrchSpec:
        env:
        - name: KAFKA_BROKER
          value: gke-gpu-cluster-kafka-brokers.default.svc.cluster.local:9092
        - name: KAFKA_INPUT_TOPIC
          value: model-input
        - name: KAFKA_OUTPUT_TOPIC
          value: model-output
      replicas: 1
    protocol: v2

  """
  with open("model.yaml", "w") as f:
    f.write(model_yaml)
  run("kubectl apply -f model.yaml", shell=True)
```
## Create component
```
deploy =kfp.components.create_component_from_func(func= deploy_k8_pod, packages_to_install=['PyYAML','kubernetes==12.0.0'])
client = kfp.Client(host='...')
client.create_run_from_pipeline_func(deploy_service,arguments = {})
```

## Error log
```
time="2022-10-07T16:14:18.136Z" level=info msg="capturing logs" argo=true
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: 
https://pip.pypa.io/warnings/venv
Container
Initialization
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f75566ee150>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/tmp.xKDfQMTaqb", line 49, in <module>
    _outputs = deploy_k8_pod(**_parsed_args)
  File "/tmp/tmp.xKDfQMTaqb", line 30, in deploy_k8_pod
    v1.list_node() 
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 16414, in list_node
    return self.list_node_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 16531, in list_node_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 377, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 243, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 216, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 75, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 828, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 828, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 828, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f75566ee150>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error: exit status 1
```

## Expected behaviour
Deploy the model and start inference

**Comment by SwathiAunooru** [comment]
We have full permission for the GKE cluster, GCP service account used, and Kubeflow pipelines.

**Comment by cliveseldon** [comment]
This seems a core connection to kube API server issue or can you clarify more how this connects to Seldon? Have you tried creating a SeldonDeployment with the same user using kubectl?

**Comment by cliveseldon** [comment]
closing for now. Please update if the issue persists.
