### ISSUE TITLE
Conda proxy config for MLflow Server

### ISSUE THREAD

**Issue by jenoOvchi** [SeldonIO/seldon-core#4386]
Hi!
I'm trying to run model with Seldon Core and MLflow server inside stricted network and it fall with next error:
2022-10-18T18:02:41.538919082+03:00 /opt/conda/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
2022-10-18T18:02:41.538928292+03:00   RequestsDependencyWarning)
2022-10-18T18:02:41.538930679+03:00
2022-10-18T18:02:41.538933893+03:00 CondaHTTPError: HTTP 000 CONNECTION FAILED for url <[https://conda.anaconda.org/conda-forge/linux-64/repodata.json>](https://conda.anaconda.org/conda-forge/linux-64/repodata.json%3E)
2022-10-18T18:02:41.538936933+03:00 Elapsed: -
2022-10-18T18:02:41.538939300+03:00
2022-10-18T18:02:41.538942273+03:00 An HTTP error occurred when trying to retrieve this URL.
2022-10-18T18:02:41.538945423+03:00 HTTP errors are often intermittent, and a simple retry will get you on your way.
2022-10-18T18:02:41.538947702+03:00 '[https://conda.anaconda.org/conda-forge/linux-64'](https://conda.anaconda.org/conda-forge/linux-64%27)
2022-10-18T18:02:41.538949902+03:00
2022-10-18T18:02:41.538952072+03:00
2022-10-18T18:02:41.609482566+03:00 Traceback (most recent call last):
2022-10-18T18:02:41.609512232+03:00   File "./conda_env_create.py", line 151, in <module>
2022-10-18T18:02:41.609518167+03:00     main(args)
2022-10-18T18:02:41.609522694+03:00   File "./conda_env_create.py", line 146, in main
2022-10-18T18:02:41.609527859+03:00     setup_env(model_folder)
2022-10-18T18:02:41.609531796+03:00   File "./conda_env_create.py", line 54, in setup_env
2022-10-18T18:02:41.609535789+03:00     create_env(env_file_path)
2022-10-18T18:02:41.609539853+03:00   File "./conda_env_create.py", line 110, in create_env
2022-10-18T18:02:41.609543875+03:00     run(cmd, shell=True, check=True)
2022-10-18T18:02:41.609548713+03:00   File "/opt/conda/lib/python3.7/subprocess.py", line 512, in run
2022-10-18T18:02:41.609552966+03:00     output=stdout, stderr=stderr)
2022-10-18T18:02:41.609557872+03:00 subprocess.CalledProcessError: Command 'conda env create -n mlflow --file /tmp/tmpjxyu_xw3/conda.yaml' returned non-zero exit status 1.

I think it is cause of conda repo is unavailable and we need to provide a config with links to the proxy repository in nexus/artifactory. Is it possible with MLflow Server or we must build an image with all preinstalled dependencies?

## To reproduce
1. Log model to MLflow within stricted network
2. Run SeldonDeployment with MLflow Server inside the same network

## Expected behaviour
Model works correctly

## Environment
Any Kubernetes and MLflow inside stricted network

**Comment by axsaucedo** [comment]
You can actually provide environment variables when you create your sdep, you will be able to provide any proxy env vars as required this way (this would be more of a conda question than a seldon one so best to check on their docs). 

The main suggestion however would be for you to use the v2 MLServer based images instead, as this is the more robust way in which you can deploy your mlflow models. https://docs.seldon.io/projects/seldon-core/en/latest/examples/mlflow_v2_protocol_end_to_end.html

**Comment by jenoOvchi** [comment]
Thanks, environment variables it's not bad.
About v2 MLServer - I don't think that package conda environment and store it in the S3 is a good idea. What happen if conda versions in IDE and deployment will be different?

**Comment by jenoOvchi** [comment]
Now we find the next problem - we were loged python repository credentials into conda_env in MLflow run and when token has expired all pods of our models not restarting (falling down with 403 error when trying to install dependencies). And now we need to relog all models with new token for python repository, create new versions and change all Seldon Deployments. It's very inconvenient...

**Comment by adriangonz** [comment]
Hey @jenoOvchi ,

The `MLmodel` config is owned by MLflow, so there's not much we can do there unfortunately. It seems like the best workaround would be to leverage the env vars suggested by @axsaucedo above. 

This is one of the many reasons why we're keen of moving towards conda-pack, and pre-generated envs in general. 

I'll close this issue, but feel free to reopen if the env vars workaround doesn't work for you.

**Comment by jenoOvchi** [comment]
We take some experiments and for us the best workaround is to put channels with the private registries within the .condarc file in the root directory of the base Seldon MLflow Server image and log models with an empty conda profile. In this case to update credentials we just need to rebuild image with the new file, update ConfigMap and restart Seldon Operator, after that all models restarts with the new credentials and all new model instances works correctly.
