### ISSUE TITLE
MLflow v2 protocol elasticnet wine example - No module named 'sklearn'

### ISSUE THREAD

**Issue by Shahar19** [SeldonIO/seldon-core#4497]
## Describe the bug
I'm evaluating Seldon core and MLSERVER for our MLFLOW model deployment.
Sorry in advance if it's a duplicate/known issue, searched a lot but couldn't find a match.
When I'm trying to run the e2e wine example (https://docs.seldon.io/projects/seldon-core/en/latest/examples/mlflow_v2_protocol_end_to_end.html), I receive the following error:
`ModuleNotFoundError: No module named 'sklearn'`
If I upload the environment.tar.gz (following the instructions), I get:
`--> Calling conda-unpack...
/opt/mlserver/environment/bin/python: 1: Syntax error: "(" unexpected
--> Disabling user-installed packages...
Dotenv file not found at './.env'
/opt/mlserver/environment/bin/python: 1: Syntax error: "(" unexpected`

- Is it a version incompatibility issue? I know that Seldon has a new V2 alpha version, mlflow has relatively new 2* versions, MLserver with 1* versions, etc.
- Is it conda pack/unpack OS incompatibility issue?
- Other issues?

I tried A LOT of approaches, but can't get it to work. please advise.

## To reproduce
1. train a model following the instructions here: https://docs.seldon.io/projects/seldon-core/en/latest/examples/mlflow_v2_protocol_end_to_end.html
2. this is the last Seldon yaml file I used:

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  name: wines
  protocol: kfserving
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          livenessProbe:
            initialDelaySeconds: 80
            failureThreshold: 200
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
          readinessProbe:
            initialDelaySeconds: 80
            failureThreshold: 200
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
    graph:
      children: []
      implementation: MLFLOW_SERVER
      modelUri: MY_MINIO MODEL
      envSecretRefName: seldon-rclone-secret
      name: classifier
    name: default
    replicas: 1
```

## Expected behaviour
MLFLOW_SERVER should install all the dependencies successfully and return the test inference results.

## Environment
* Cloud Provider: Minikube + hyperkit --kubernetes-version=v1.24.8 --cpus 4 --memory 8192
* Kubernetes Cluster Version:
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:31:40Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Deployed Seldon System Images: docker.io/seldonio/seldon-core-operator:1.15.0
* with Istio ingress, minio (followed Seldon instructions)
* mlflow (latest) is deployed using my custom image on the minikube cluster and works as expected.
additional versions: macOS (12.6), conda 4.10.3, python 3.8.10

## Model Details
* Images of your model:
```
apiVersion: v1
items:
- apiVersion: machinelearning.seldon.io/v1
  kind: SeldonDeployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"machinelearning.seldon.io/v1alpha2","kind":"SeldonDeployment","metadata":{"annotations":{},"name":"mlflow","namespace":"seldon"},"spec":{"name":"wines","predictors":[{"componentSpecs":[{"spec":{"containers":[{"livenessProbe":{"failureThreshold":200,"httpGet":{"path":"/health/ping","port":"http","scheme":"HTTP"},"initialDelaySeconds":80,"periodSeconds":5,"successThreshold":1},"name":"classifier","readinessProbe":{"failureThreshold":200,"httpGet":{"path":"/health/ping","port":"http","scheme":"HTTP"},"initialDelaySeconds":80,"periodSeconds":5,"successThreshold":1}}]}}],"graph":{"children":[],"envSecretRefName":"seldon-rclone-secret","implementation":"MLFLOW_SERVER","modelUri":"s3://mlflow/0/my_experiment_ID/artifacts/model","name":"classifier"},"name":"default","replicas":1}],"protocol":"kfserving"}}
    creationTimestamp: "2022-12-11T09:26:08Z"
    generation: 1
    name: mlflow
    namespace: seldon
    resourceVersion: "70892"
    uid: 7b9c7d82-b5b4-4c91-b389-b400b7345fcc
  spec:
    name: wines
    predictors:
    - componentSpecs:
      - spec:
          containers:
          - livenessProbe:
              failureThreshold: 200
              httpGet:
                path: /health/ping
                port: http
                scheme: HTTP
              initialDelaySeconds: 80
              periodSeconds: 5
              successThreshold: 1
            name: classifier
            readinessProbe:
              failureThreshold: 200
              httpGet:
                path: /health/ping
                port: http
                scheme: HTTP
              initialDelaySeconds: 80
              periodSeconds: 5
              successThreshold: 1
      graph:
        children: []
        envSecretRefName: seldon-rclone-secret
        implementation: MLFLOW_SERVER
        modelUri: s3://mlflow/0/my_experiment_ID/artifacts/model
        name: classifier
      name: default
      replicas: 1
    protocol: kfserving
  status:
    address:
      url: http://mlflow-default.seldon.svc.cluster.local:8000/v2/models/classifier/infer
    conditions:
    - lastTransitionTime: "2022-12-11T09:26:08Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: DeploymentsReady
    - lastTransitionTime: "2022-12-11T09:26:08Z"
      reason: No HPAs defined
      status: "True"
      type: HpasReady
    - lastTransitionTime: "2022-12-11T09:26:08Z"
      reason: No KEDA resources defined
      status: "True"
      type: KedaReady
    - lastTransitionTime: "2022-12-11T09:26:08Z"
      reason: No PDBs defined
      status: "True"
      type: PdbsReady
    - lastTransitionTime: "2022-12-11T09:26:08Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Ready
    - lastTransitionTime: "2022-12-11T09:26:08Z"
      reason: Not all services created
      status: "False"
      type: ServicesReady
    deploymentStatus:
      mlflow-default-0-classifier:
        replicas: 1
    replicas: 1
    state: Creating
kind: List
metadata:
  resourceVersion: ""
```
* Logs of your model:

```
Defaulted container "classifier" out of: classifier, seldon-container-engine, classifier-model-initializer (init)
Environment tarball not found at '/mnt/models/environment.tar.gz'
Environment not found at './environment'
Dotenv file not found at './.env'
2022-12-11 08:30:20,852 [mlserver] INFO - Using asyncio event-loop policy: uvloop
2022-12-11 08:30:21,540 [mlserver.parallel] DEBUG - Starting response processing loop...
INFO:     Started server process [1]
INFO:     Waiting for application startup.
2022-12-11 08:30:21,575 [mlserver.metrics] INFO - Metrics server running on http://0.0.0.0:6000
2022-12-11 08:30:21,575 [mlserver.metrics] INFO - Prometheus scraping endpoint can be accessed on http://0.0.0.0:6000/prometheus
INFO:     Started server process [1]
INFO:     Waiting for application startup.
2022/12/11 08:30:21 WARNING mlflow.pyfunc: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - cloudpickle (current: 2.1.0, required: cloudpickle==2.2.0)
 - scikit-learn (current: uninstalled, required: scikit-learn==1.2.0)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
INFO:     Application startup complete.
2022-12-11 08:30:21,691 [mlserver.grpc] INFO - gRPC server running on http://0.0.0.0:9500
INFO:     Application startup complete.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.8/site-packages/mlserver/cli/main.py", line 44, in start
    await server.start(models_settings)
  File "/usr/local/lib/python3.8/site-packages/mlserver/server.py", line 98, in start
    await asyncio.gather(
  File "/usr/local/lib/python3.8/site-packages/mlserver/registry.py", line 272, in load
    return await self._models[model_settings.name].load(model_settings)
  File "/usr/local/lib/python3.8/site-packages/mlserver/registry.py", line 143, in load
    await self._load_model(new_model)
  File "/usr/local/lib/python3.8/site-packages/mlserver/registry.py", line 151, in _load_model
    await model.load()
  File "/usr/local/lib/python3.8/site-packages/mlserver_mlflow/runtime.py", line 117, in load
    self._model = mlflow.pyfunc.load_model(model_uri)
  File "/usr/local/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 735, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 479, in _load_pyfunc
    return _load_model_from_local_file(path=path, serialization_format=serialization_format)
  File "/usr/local/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 437, in _load_model_from_local_file
    return cloudpickle.load(f)
ModuleNotFoundError: No module named 'sklearn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 638, in lifespan
    await receive()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/local/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
asyncio.exceptions.CancelledError

ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.8/site-packages/mlserver/cli/main.py", line 44, in start
    await server.start(models_settings)
  File "/usr/local/lib/python3.8/site-packages/mlserver/server.py", line 98, in start
    await asyncio.gather(
  File "/usr/local/lib/python3.8/site-packages/mlserver/registry.py", line 272, in load
    return await self._models[model_settings.name].load(model_settings)
  File "/usr/local/lib/python3.8/site-packages/mlserver/registry.py", line 143, in load
    await self._load_model(new_model)
  File "/usr/local/lib/python3.8/site-packages/mlserver/registry.py", line 151, in _load_model
    await model.load()
  File "/usr/local/lib/python3.8/site-packages/mlserver_mlflow/runtime.py", line 117, in load
    self._model = mlflow.pyfunc.load_model(model_uri)
  File "/usr/local/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 735, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 479, in _load_pyfunc
    return _load_model_from_local_file(path=path, serialization_format=serialization_format)
  File "/usr/local/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 437, in _load_model_from_local_file
    return cloudpickle.load(f)
ModuleNotFoundError: No module named 'sklearn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 638, in lifespan
    await receive()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/local/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
asyncio.exceptions.CancelledError

Traceback (most recent call last):
  File "/usr/local/bin/mlserver", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/mlserver/cli/main.py", line 79, in main
    root()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mlserver/cli/main.py", line 20, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.8/site-packages/mlserver/cli/main.py", line 44, in start
    await server.start(models_settings)
  File "/usr/local/lib/python3.8/site-packages/mlserver/server.py", line 98, in start
    await asyncio.gather(
  File "/usr/local/lib/python3.8/site-packages/mlserver/registry.py", line 272, in load
    return await self._models[model_settings.name].load(model_settings)
  File "/usr/local/lib/python3.8/site-packages/mlserver/registry.py", line 143, in load
    await self._load_model(new_model)
  File "/usr/local/lib/python3.8/site-packages/mlserver/registry.py", line 151, in _load_model
    await model.load()
  File "/usr/local/lib/python3.8/site-packages/mlserver_mlflow/runtime.py", line 117, in load
    self._model = mlflow.pyfunc.load_model(model_uri)
  File "/usr/local/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 735, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 479, in _load_pyfunc
    return _load_model_from_local_file(path=path, serialization_format=serialization_format)
  File "/usr/local/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 437, in _load_model_from_local_file
    return cloudpickle.load(f)
ModuleNotFoundError: No module named 'sklearn'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
```

If I follow the conda-pack instructions and uploading the environment.tar.gz to the relevant model in minio, I'm getting:
this is the end of the pod's log:

```
bin/activate
bin/deactivate
bin/conda-unpack
--> Sourcing new environment at ./environment...
--> Calling conda-unpack...
/opt/mlserver/environment/bin/python: 1: Syntax error: "(" unexpected
--> Disabling user-installed packages...
Dotenv file not found at './.env'
/opt/mlserver/environment/bin/python: 1: Syntax error: "(" unexpected
```

I was also able to serve the mlflow model locally with mlserver, and was able to serve the model using seldon v1 protocol.

Thanks a lot in advance!!!

**Comment by adriangonz** [comment]
Hey @Shahar19 ,

From that `Syntax error` message, it may be an OS compatibility issue. Are you running this from MacOS by any chance? 

The env tarball is OS dependent,  as it packs a few system libs. Therefore, it's best if you can create it from a Linux / Docker env.

**Comment by adriangonz** [comment]
Hey @Shahar19 ,

Any general-purpose Linux Docker image should do really, like the Ubuntu or Debian ones.

**Comment by cliveseldon** [comment]
Closing this for now. Please reopen if needed.
