### ISSUE TITLE
ConnectionResetError(104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by onlyone2019** [SeldonIO/seldon-core#4734]
# Describe the bug
I followed this [tutorial](https://github.com/SeldonIO/seldon-core/blob/8004de80ec447d5337d78ef630328584b3177829/examples/models/chainer_mnist/chainer_mnist.ipynb)  to deploy mnist-serve to my k8s cluster. But something unexpected happened when I use `seldon-core-api-tester contract.json 10.96.134.181 5001 seldon-deployment-example-chainer-mnist-predictor --namespace default -p` to test it.

## The Error reminded
```
$$ seldon-core-api-tester contract.json 10.96.134.181 5001 seldon-deployment-example-chainer-mnist-predictor --namespace default -p

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
----------------------------------------
SENDING NEW REQUEST:

[[1.]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/seldon-core-api-tester", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/seldon_core/api_tester.py", line 144, in main
    run_predict(args)
  File "/usr/local/lib/python3.8/dist-packages/seldon_core/api_tester.py", line 98, in run_predict
    response_predict = sc.predict(
  File "/usr/local/lib/python3.8/dist-packages/seldon_core/seldon_client.py", line 367, in predict
    return rest_predict_gateway(**k)
  File "/usr/local/lib/python3.8/dist-packages/seldon_core/seldon_client.py", line 1546, in rest_predict_gateway
    response_raw = requests.post(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

# Environment
The version of my k8s cluster is:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T21:01:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
``` 
Other Information:
```
$$ kubectl get deploy -A

NAMESPACE       NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
default         seldon-daa23374823e7af1299eb0c896e70983   1/1     1            1           4h28m
kube-system     calico-kube-controllers                   1/1     1            1           19d
kube-system     coredns                                   2/2     2            2           19d
kube-system     seldon-spartakus-volunteer                1/1     1            1           5h10m
seldon-system   seldon-controller-manager                 1/1     1            1           5h10m

$$ kubectl get svc -A

NAMESPACE       NAME                                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default         kubernetes                                          ClusterIP   10.96.0.1       <none>        443/TCP                  19d
default         seldon-a70ef06a0e57c4bdde4739695d9e3e7e             ClusterIP   10.96.67.139    <none>        9000/TCP,9500/TCP        4h33m
default         seldon-deployment-example-chainer-mnist-predictor   ClusterIP   10.96.134.181   <none>        8000/TCP,5001/TCP        4h33m
kube-system     kube-dns                                            ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   19d
seldon-system   seldon-webhook-service                              ClusterIP   10.96.11.89     <none>        443/TCP                  5h15m

$$ kubectl get pod -A

NAMESPACE       NAME                                                       READY   STATUS    RESTARTS   AGE
default         seldon-daa23374823e7af1299eb0c896e70983-5789cbd558-tg6dv   2/2     Running   0          4h34m
kube-system     calico-kube-controllers-577f77cb5c-f2mw9                   1/1     Running   28         19d
kube-system     calico-node-twjt6                                          1/1     Running   1          19d
kube-system     coredns-5897cd56c4-ksxsh                                   1/1     Running   1          19d
kube-system     coredns-5897cd56c4-wscss                                   1/1     Running   1          19d
kube-system     etcd-master                                                1/1     Running   3          19d
kube-system     kube-apiserver-master                                      1/1     Running   10         19d
kube-system     kube-controller-manager-master                             1/1     Running   28         19d
kube-system     kube-proxy-4xth8                                           1/1     Running   1          19d
kube-system     kube-scheduler-master                                      1/1     Running   26         19d
kube-system     seldon-spartakus-volunteer-5b57b95596-x6876                1/1     Running   0          5h15m
seldon-system   seldon-controller-manager-6b7b8b8b6c-z5jld                 1/1     Running   7          5h15m

```

# Expected behaviour
The mirror dependency and the packaging process are exactly the same as this [tutorial](https://github.com/SeldonIO/seldon-core/blob/8004de80ec447d5337d78ef630328584b3177829/examples/models/chainer_mnist/chainer_mnist.ipynb). 

And the following tests have passed.
```
docker run --name "mnist_predictor" -d --rm -p 5000:5000 chainer-mnist:0.1
seldon-core-tester contract.json 0.0.0.0 5000 -p
```

Expected Output should like this:
```
----------------------------------------
SENDING NEW REQUEST:
[[0.072 0.145 0.863 0.094 0.234 ...]]

RECEIVED RESPONSE:
data {
  names: ...
  ndarray {
    values {
      list_value {
        values {
          number_value: -11.87045955657959
        }
        ...
      }
    }
  }
}
```

**Comment by cliveseldon** [comment]
Have you tried calling the SeldonDeployment with curl?

**Comment by onlyone2019** [comment]
Yes，I have tried curl and got some feedback:
```
$$ curl 10.96.134.181:5001 --http0.9 --output tmp.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15    0    15    0     0  15000      0 --:--:-- --:--:-- --:--:-- 15000
curl: (56) Recv failure: 连接被对方重设
```

**Comment by onlyone2019** [comment]
Yes，I have tried curl and got some feedback:
```
$$ curl 10.96.134.181:5001 --http0.9 --output tmp.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15    0    15    0     0  15000      0 --:--:-- --:--:-- --:--:-- 15000
curl: (56) Recv failure: 连接被对方重设
```

**Comment by cliveseldon** [comment]
Closing - please recomment will more logs if still an issue with latest core v1
