### ISSUE TITLE
MLFlow Custom Pyfunc Model

### ISSUE THREAD

**Issue by joshuajorel** [SeldonIO/seldon-core#4839]
I created an MLFlow Pyfunc model with the following defintion:

```
import mlflow.pyfunc

class SimpleModel(mlflow.pyfunc.PythonModel):
    """
    Simple model for testing
    """
    def __init__(self, model):
        self.model = model
        
    def predict(self, context, inputs):
        sample_output = {
            "output": 123
        }
        
        return sample_output
```

I saved this model to my local machine and started MLServer. I wanted to send this payload:
```
#/v2/models/{model}/infer
{
"inputs": [
        {
            "name": "simple-model", 
            "shape": [1], 
            "datatype": "string", 
            "data": ["test"], 
        }
    ]
}
```
```
#/invocations
{
"inputs": [{}]
}
```

I called both the `/v2/models/{model}/infer` and `/invocations` endpoint, but I get the following error:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/starlette_exporter/middleware.py", line 307, in __call__
    await self.app(scope, receive, wrapped_send)
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/mlserver/rest/app.py", line 42, in custom_route_handler
    return await original_route_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/mlserver/rest/endpoints.py", line 99, in infer
    inference_response = await self._data_plane.infer(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/mlserver/handlers/dataplane.py", line 103, in infer
    prediction = await model.predict(payload)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/mlserver/parallel/model.py", line 54, in predict
    inference_response = await self._send(ModelMethods.Predict.value, payload)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/mlserver/parallel/model.py", line 71, in _send
    response_message = await self._dispatcher.dispatch_request(req_message)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/mlserver/parallel/dispatcher.py", line 99, in dispatch_request
    self._workers_queue_monitor(worker, wpid)
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/site-packages/mlserver/parallel/dispatcher.py", line 114, in _workers_queue_monitor
    queue_size = worker._requests.qsize()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/mlserver/lib/python3.11/multiprocessing/queues.py", line 126, in qsize
    return self._maxsize - self._sem._semlock._get_value()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError
```

Am I doing anything wrong or is there any issues with my input format or any missing parameters from my model? 

Environment details:
MacOS, conda 4.12.0, MLFlow 2.3.1, MLServer 1.3.2

**Comment by joshuajorel** [comment]
Apologies, wrote this issue in the wrong project.
