### ISSUE TITLE
Scheduler panic on server restart with model loaded

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#4931]
Reproduced by killing mlserver after model sucessfully loaded on k8s.

```
│ panic: runtime error: invalid memory address or nil pointer dereference                                                                                                 │
│ [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a0244d]                                                                                                 │
│                                                                                                                                                                         │
│ goroutine 190 [running]:                                                                                                                                                │
│ github.com/seldonio/seldon-core/scheduler/v2/pkg/envoy/processor.(*IncrementalProcessor).updateEnvoyForModelVersion(0xc0005c1ad0, {0xc0020360a0, 0x4}, 0xc0018d5d00, 0x │
│     /build/scheduler/pkg/envoy/processor/incremental.go:264 +0xcd                                                                                                       │
│ github.com/seldonio/seldon-core/scheduler/v2/pkg/envoy/processor.(*IncrementalProcessor).addModelTraffic(0xc0005c1ad0, {0xc0020360a0, 0x4}, 0xc001849fb0, 0x1a44f18?, 0 │
│     /build/scheduler/pkg/envoy/processor/incremental.go:337 +0x652                                                                                                      │
│ github.com/seldonio/seldon-core/scheduler/v2/pkg/envoy/processor.(*IncrementalProcessor).addModel(0xc0005c1ad0, 0xc001849fb0)                                           │
│     /build/scheduler/pkg/envoy/processor/incremental.go:393 +0x305                                                                                                      │
│ github.com/seldonio/seldon-core/scheduler/v2/pkg/envoy/processor.(*IncrementalProcessor).modelUpdate(0xc0005c1ad0, {0xc0020360a0, 0x4})                                 │
│     /build/scheduler/pkg/envoy/processor/incremental.go:592 +0xa8b                                                                                                      │
│ github.com/seldonio/seldon-core/scheduler/v2/pkg/envoy/processor.(*IncrementalProcessor).handleModelEvents.func1()                                                      │
│     /build/scheduler/pkg/envoy/processor/incremental.go:183 +0x54                                                                                                       │
│ created by github.com/seldonio/seldon-core/scheduler/v2/pkg/envoy/processor.(*IncrementalProcessor).handleModelEvents                                                   │
│     /build/scheduler/pkg/envoy/processor/incremental.go:182 +0x1b8  
```

**Comment by cliveseldon** [comment]
Fixed
