### ISSUE TITLE
seldon 0.2.3 - nfs volume in seldon graph failing in validation

### ISSUE THREAD

**Issue by klalit** [SeldonIO/seldon-core#504]
Error:
com.google.protobuf.InvalidProtocolBufferException: Cannot find field: nfs in message k8s.io.api.core.v1.Volume
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1292)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.merge(JsonFormat.java:1252)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:1797)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeRepeatedField(JsonFormat.java:1541)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1460)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1294)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.merge(JsonFormat.java:1252)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:1797)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1462)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1294)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.merge(JsonFormat.java:1252)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:1797)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeRepeatedField(JsonFormat.java:1541)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1460)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1294)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.merge(JsonFormat.java:1252)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:1797)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeRepeatedField(JsonFormat.java:1541)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1460)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1294)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.merge(JsonFormat.java:1252)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:1797)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1462)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1294)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.merge(JsonFormat.java:1252)
	at io.seldon.clustermanager.pb.JsonFormat$ParserImpl.merge(JsonFormat.java:1126)
	at io.seldon.clustermanager.pb.JsonFormat$Parser.merge(JsonFormat.java:305)
	at io.seldon.clustermanager.k8s.SeldonDeploymentUtils.jsonToSeldonDeployment(SeldonDeploymentUtils.java:44)
	at io.seldon.clustermanager.k8s.SeldonDeploymentWatcher.watchSeldonMLDeployments(SeldonDeploymentWatcher.java:165)
	at io.seldon.clustermanager.k8s.SeldonDeploymentWatcher.watch(SeldonDeploymentWatcher.java:197)
	at sun.reflect.GeneratedMethodAccessor534.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

========================Yaml==============================
apiVersion: machinelearning.seldon.io/v1alpha2
        kind: SeldonDeployment
        metadata:
          name: "{{workflow.parameters.model-name}}"
          labels:
            app: seldon
          namespace: kubeflow
        spec:
          name: "{{workflow.parameters.model-name}}-deployment"
          predictors:
          - componentSpecs:
            - spec:
                containers:
                  - image: "{{workflow.parameters.model-name}}:v0.1"
                    imagePullPolicy: IfNotPresent
                    name: "{{workflow.parameters.model-name}}"
                    volumeMounts:
                      - name: "pvol44"
                        mountPath: "/mnt/vol"
                volumes:
                  - nfs:
                      path: /var/persistvol/pvol4
                      server: <<>>
                    name: "pvol44"
            graph:
              children: []
              endpoint:
                type: REST
              name: "{{workflow.parameters.model-name}}"
              type: MODEL
            labels:
              version: v1
            name: "{{workflow.parameters.model-name}}"
            replicas: 1

**Comment by cliveseldon** [comment]
You can solve this by using the explicit `volumeSource` way of writing this. See  [here](https://github.com/SeldonIO/seldon-core/issues/116#issuecomment-373206582) for an example.

This is because at present we use the official protobuffer definitions of the k8s API for parsing. This will be solved when this is changed and is planned for 0.2.8.

**Comment by klalit** [comment]
thank you.. it means i'll have to convert the yaml to json?

**Comment by cliveseldon** [comment]
No You can use the Yaml version of this.

**Comment by klalit** [comment]
thank you it works..
