### ISSUE TITLE
Could you release seldon-core 1.17.1 or 1.18.0 so PyYAML not supporting PEP517 can be avoided?

### ISSUE THREAD

**Issue by ysk24ok** [SeldonIO/seldon-core#5091]
The master branch:

https://github.com/SeldonIO/seldon-core/blob/b5b5a10979220a19da312bab138ad51341ef2f21/python/setup.py#L43

seldon-core v1.17.0

https://github.com/SeldonIO/seldon-core/blob/5f3687efa4d3434036b6a65177bfacf5bb3beebb/python/setup.py#L43

I'm using seldon-core v1.17.0 and Python 3.10. PyYAML<5.5 limitation causes the following error when I run `poetry install`.

```
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
      super().run_command(command)
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 319, in run
      self.find_sources()
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 327, in find_sources
      mm.run()
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 549, in run
      self.add_defaults()
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 587, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
      super().add_defaults()
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
    File "<string>", line 201, in get_source_files
    File "/tmp/tmp82ussr9p/.venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources


  at /usr/local/lib/python3.10/site-packages/poetry/installation/chef.py:152 in _prepare
      148│
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│
      151│             if error is not None:
    → 152│                 raise error from None
      153│
      154│             return path
      155│
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pyyaml (5.4.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyyaml (==5.4.1)"'.
```

With PyYAML 6, there are wheels for Python 3.10 so no local build at install time will occur.
Could you release seldon-core v1.17.1 or v1.18.0 as soon as possible? I'm blocked by this issue.

**Comment by ysk24ok** [comment]
https://pypi.org/project/seldon-core/1.17.1/
1.17.1 has been released which can use PyYAML 6. Closing the issue.
