### ISSUE TITLE
ModelUri is None when parameters specified in the SeldonDeployment

### ISSUE THREAD

**Issue by dileepranganathan** [SeldonIO/seldon-core#838]
ModelUri is coming as None when parameters specified in the SeldonDeployment spec.

```
I0830 17:36:03.203464 140531701827328 microservice.py:216] Importing SKLearnServer
Model uri: None
method: predict
load
Traceback (most recent call last):
  File "/usr/local/bin/seldon-core-microservice", line 11, in <module>
    load_entry_point('seldon-core', 'console_scripts', 'seldon-core-microservice')()
  File "/microservice/python/seldon_core/microservice.py", line 229, in main
    user_object = user_class(**parameters)
  File "/microservice/SKLearnServer.py", line 23, in __init__
    self.load()
  File "/microservice/SKLearnServer.py", line 27, in load
    model_file = os.path.join(seldon_core.Storage.download(self.model_uri), JOBLIB_FILE)
  File "/microservice/python/seldon_core/storage.py", line 41, in download
    if uri.startswith(_LOCAL_PREFIX) or os.path.exists(uri):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

The deployment used is
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: sklearn
spec:
  name: vcmts-power
  predictors:
  - graph:
      children: []
      implementation: SKLEARN_SERVER
      modelUri: s3://models/sklearn/power
      envSecretRefName: s3-secret
      name: classifier
      parameters:
        - name: method
          type: STRING
          value: predict
    name: default
    replicas: 1
```

Environment variable is missing the model uri part.
name: PREDICTIVE_UNIT_PARAMETERS
value: '[{"name":"method","value":"predict","type":"STRING"}]'

**Comment by cliveseldon** [comment]
Should be fixed in latest master. Can you test with seldonio/seldon-core-operator:0.4.1-SNAPSHOT ?

**Comment by cliveseldon** [comment]
Close - please reopen if still issue

**Comment by Shivdutta** [comment]
getting the same error in steps graph deployment

apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: graph-metadata-two-levels
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/sklearnserver:1.13.1
          name: node-one          
        - image: k3d-myregistry.localhost:12345/shiv/mymodel:v1
          name: node-two
    graph:
      name: node-one
      type: MODEL
      implementation: SKLEARN_SERVER
      modelUri: s3://mlflow/12345612345612345612345612345612/artifacts/model/
      envSecretRefName: seldon-init-container-secret
      name: classifier
      parameters:
        - name: method
          type: STRING
          value: predict
      children:
      - name: node-two
        type: MODEL
        children: []
    name: example
    replicas: 1


node one is sklearn server
node two is custom model

(base) shivdutta@aiwlaptp041:~/Documents/k3d$ kubectl get pods
NAME                                                       READY   STATUS             RESTARTS   AGE
seldon-6f407027272e1028c8e7d1e48c5533f3-6ff8ccd576-6x6fn   3/4     CrashLoopBackOff   7          15m





(base) shivdutta@aiwlaptp041:~/Documents/k3d$ kubectl logs -f seldon-6f407027272e1028c8e7d1e48c5533f3-6ff8ccd576-6x6fn -c node-one
/opt/conda/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
starting microservice
2022-05-27 11:19:20,861 - seldon_core.microservice:main:211 - INFO:  Starting microservice.py:main
2022-05-27 11:19:20,861 - seldon_core.microservice:main:212 - INFO:  Seldon Core version: 1.13.1
2022-05-27 11:19:20,863 - seldon_core.microservice:main:367 - INFO:  Parse JAEGER_EXTRA_TAGS []
2022-05-27 11:19:20,863 - seldon_core.microservice:main:370 - INFO:  Annotations: {}
2022-05-27 11:19:20,863 - seldon_core.microservice:main:374 - INFO:  Importing SKLearnServer
2022-05-27 11:19:20,891 - SKLearnServer:__init__:21 - INFO:  Model uri: None
2022-05-27 11:19:20,891 - SKLearnServer:__init__:22 - INFO:  method: predict_proba
2022-05-27 11:19:20,891 - SKLearnServer:load:26 - INFO:  load
2022-05-27 11:19:20,891 - root:download:31 - INFO:  Copying contents of None to local
Traceback (most recent call last):
  File "/opt/conda/bin/seldon-core-microservice", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/seldon_core/microservice.py", line 384, in main
    user_object = user_class(**parameters)
  File "/microservice/SKLearnServer.py", line 23, in __init__
    self.load()
  File "/microservice/SKLearnServer.py", line 28, in load
    seldon_core.Storage.download(self.model_uri), JOBLIB_FILE
  File "/opt/conda/lib/python3.7/site-packages/seldon_core/storage.py", line 34, in download
    if uri.startswith(_LOCAL_PREFIX) or os.path.exists(uri):
AttributeError: 'NoneType' object has no attribute 'startswith'
(base) shivdutta@aiwlaptp041:~/Documents/k3d$ 


Seldon version   Seldon Core version: 1.13.1
