### ISSUE TITLE
Requesting the endpoint  only works the first time after the endpoint is available, the subsequent requests give "AttributeError: 'Logic' object has no attribute 'predict_raw'"

### ISSUE THREAD

**Issue by PrathamSolanki** [SeldonIO/seldon-core#860]
Once the endpoint is available, I get the predictions when I request them for the first time. However, when I request subsequent times I get:

```
{
  "code": 103,
  "info": "Status code: 500 Reason: ",
  "reason": "Microservice error",
  "status": "FAILURE"
}
```

This is really weird. These are the logs of my pod:

```
starting microservice
2019-09-12 13:17:12,188 - seldon_core.microservice:main:154 - INFO:  Starting microservice.py:main
2019-09-12 13:17:12,190 - seldon_core.microservice:load_annotations:104 - INFO:  Found annotation deployment_version:v1 
2019-09-12 13:17:12,190 - seldon_core.microservice:load_annotations:104 - INFO:  Found annotation kubernetes.io/config.seen:2019-09-12T13:17:07.492155558Z 
2019-09-12 13:17:12,190 - seldon_core.microservice:load_annotations:104 - INFO:  Found annotation kubernetes.io/config.source:api 
2019-09-12 13:17:12,190 - seldon_core.microservice:load_annotations:104 - INFO:  Found annotation predictor_version:v1 
2019-09-12 13:17:12,190 - seldon_core.microservice:load_annotations:104 - INFO:  Found annotation project_name:Pipeline 
2019-09-12 13:17:12,190 - seldon_core.microservice:load_annotations:104 - INFO:  Found annotation prometheus.io/path:/prometheus 
2019-09-12 13:17:12,190 - seldon_core.microservice:load_annotations:104 - INFO:  Found annotation prometheus.io/port:8000 
2019-09-12 13:17:12,190 - seldon_core.microservice:load_annotations:104 - INFO:  Found annotation prometheus.io/scrape:true 
2019-09-12 13:17:12,191 - seldon_core.microservice:main:185 - INFO:  Annotations: {'deployment_version': 'v1', 'kubernetes.io/config.seen': '2019-09-12T13:17:07.492155558Z', 'kubernetes.io/config.source': 'api', 'predictor_version': 'v1', 'project_name': 'Pipeline', 'prometheus.io/path': '/prometheus', 'prometheus.io/port': '8000', 'prometheus.io/scrape': 'true'}
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/seldon-core-microservice", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/seldon_core/microservice.py", line 189, in main
    logger.info("Importing ",args.interface_name)
Message: 'Importing '
Arguments: ('Logic',)
Using TensorFlow backend.
2019-09-12 13:17:12,412 - seldon_core.microservice:main:226 - INFO:  REST microservice running on port 9001
2019-09-12 13:17:12,413 - seldon_core.microservice:main:260 - INFO:  Starting servers
 * Serving Flask app "seldon_core.wrapper" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2019-09-12 13:17:12,446 - werkzeug:_log:122 - INFO:   * Running on http://0.0.0.0:9001/ (Press CTRL+C to quit)
WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-09-12 13:17:41,072 - tensorflow:new_func:323 - WARNING:  From /usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3733: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2019-09-12 13:17:41,697 - tensorflow:new_func:506 - WARNING:  From /usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3733: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2019-09-12 13:17:41.816819: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-12 13:17:41.823848: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2019-09-12 13:17:41.824328: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x7f449cb3d960 executing computations on platform Host. Devices:
2019-09-12 13:17:41.824616: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-09-12 13:17:42,083 - tensorflow:new_func:323 - WARNING:  From /usr/local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-09-12 13:17:45,565 - werkzeug:_log:122 - INFO:  127.0.0.1 - - [12/Sep/2019 13:17:45] "POST /predict HTTP/1.1" 200 -
2019-09-12 13:17:46,931 - flask.app:log_exception:1761 - ERROR:  Exception on /predict [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/seldon_core/seldon_methods.py", line 35, in predict
    return user_model.predict_raw(request)
AttributeError: 'Logic' object has no attribute 'predict_raw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/seldon_core/user_model.py", line 140, in client_predict
    return user_model.predict(features, feature_names, **kwargs)
TypeError: predict() got an unexpected keyword argument 'meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1092, in _run
    subfeed, allow_tensor=True, allow_operation=False)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3478, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3557, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("Placeholder:0", shape=(15, 50), dtype=float32) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/seldon_core/wrapper.py", line 39, in Predict
    responseProto = seldon_core.seldon_methods.predict(user_model, requestProto)
  File "/usr/local/lib/python3.6/site-packages/seldon_core/seldon_methods.py", line 38, in predict
    client_response = client_predict(user_model, features, datadef.names, meta=meta)
  File "/usr/local/lib/python3.6/site-packages/seldon_core/user_model.py", line 142, in client_predict
    return user_model.predict(features, feature_names)
  File "/microservice/Logic.py", line 19, in predict
    model = load_model(byte_stream)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/saving.py", line 554, in load_model
    model = load_from_binary_h5py(load_function, filepath)
  File "/usr/local/lib/python3.6/site-packages/keras/utils/io_utils.py", line 402, in load_from_binary_h5py
    return load_function(h5_file)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/saving.py", line 553, in load_function
    return _deserialize_model(H5Dict(h5file), custom_objects, compile)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/saving.py", line 305, in _deserialize_model
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2732, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1095, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder:0", shape=(15, 50), dtype=float32) is not an element of this graph.
2019-09-12 13:17:46,939 - werkzeug:_log:122 - INFO:  127.0.0.1 - - [12/Sep/2019 13:17:46] "POST /predict HTTP/1.1" 500 -
```

I'd highly appreciate any help.

**Comment by cliveseldon** [comment]
Which version of Seldon are you running?
Do you have the resource yaml you used or an example?

It looks like a Tensorflow error in the stack trace?

**Comment by elouayas** [comment]
The issue was on this line : 
```
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder:0", shape=(15, 50), dtype=float32) is not an element of this graph.

```
It is a well known keras issue, that was solved with that solution : 
https://github.com/keras-team/keras/issues/6462
